### ISSUE TITLE
timer reschedule error message

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#100]
I inadvertently called `timer.reschedule an_int_variable` instead of `timer.reschedule `an_int_variable.seconds` and this happened:

```
org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `to_ms' for 50:Integer
Did you mean?  to_s
               to_c
               to_r
               to_f
               to_i
	at RUBY.reschedule(/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-2.9.2/lib/openhab/core/dsl/timers.rb:67) ~[?:?]
	at RUBY.<main>(<script>:149) ~[?:?]
	at RUBY.initialize(/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-2.9.2/lib/openhab/core/dsl/timers.rb:46) ~[?:?]
	at org.jruby.ext.thread.Mutex.synchronize(org/jruby/ext/thread/Mutex.java:164) ~[?:?]
	at RUBY.initialize(/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-2.9.2/lib/openhab/core/dsl/timers.rb:45) ~[?:?]
```

Should we take bare integer argument to reschedule as seconds? I know it's a bit ambiguous though. Or at the least, issue a better error message?

**Comment by boc-tothefuture** [comment]
I think better error message is the way here.. not sure we want to guess if it seconds or milliseconds.

**Comment by jimtng** [comment]
How about this:

```
07:30:50.378 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/ruby/personal/test.rb': org.jruby.embed.EvalFailedException: (ArgumentError) Invalid duration argument. It does not respond to to_ms
```

**Comment by jimtng** [comment]
I wish errors like these would include the stack trace even when the log level of `org.openhab.core.automation` is set to DEFAULT/info. I just want to know the line number of the offending code.

Setting the log level for org.openhab.core.automation to DEBUG generates too many noise

I need to pay closer attention to how jython somehow managed to do this without DEBUG

**Comment by jimtng** [comment]
With the new Java Duration, the error message is now:
```
Caused by: org.jruby.exceptions.NameError: (NameError) no method 'plus' for arguments (org.jruby.RubyFixnum) on Java::JavaTime::ZonedDateTime
  available overloads:
    (java.time.temporal.TemporalAmount)
    (java.time.temporal.TemporalAmount)
    (java.time.temporal.TemporalAmount)
```

To improve this error message, we'd need to do checks in a few places: 
* after
* changed duration
* cron

Is it worth doing it or leave it as is?

**Comment by boc-tothefuture** [comment]
Probably worth doing.. just an ArgumentError if type.is_a? is not Duration, correct?

**Comment by jimtng** [comment]
We could accept descendants of TemporalAmount (Duration and Period)
