### ISSUE TITLE
Checking the existence of an item

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#101]
Is there a more elegant way to check if an item exists, given a name?

Currently, items['ANonExistentItem'] will cause an exception. I'd have to rescue the exception to proceed.

It would be good I think if items['ANonExistentItem'] will simply return nil.

**Comment by boc-tothefuture** [comment]
Does items.include? 'ANonExistentItem' work (items is a ruby set).

**Comment by jimtng** [comment]
> Does items.include? 'ANonExistentItem' work (items is a ruby set).

Yes It would work. I'd include this in the docs. I know it's a trivial thing, but it's helpful for some people... like me :)

Making items['ANonExistentItem'] to return nil would be consistent with Hash behaviour though.

**Comment by jimtng** [comment]
Sorry, I've just tested `items.include? 'Something'`. It doesn't matter whether `Something` is an existing item or non existent, it still raised an error:

```
Switch                TestItem1
```

```ruby
rule 'rule1 ' do
  on_start
  run do
    logger.info("on? #{items['TestItem1'].on?}")
    logger.info("include? #{items.include?('TestItem1')}")
  end
end
```

```
07:04:02.816 [INFO ] [.OpenHAB::Core::DSL::Rule::RuleConfig] - on? false
07:04:02.846 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/ruby/personal/test.rb': org.jruby.embed.EvalFailedException: java.lang.NumberFormatException: Character T is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
```

**Comment by boc-tothefuture** [comment]
Seems very odd that include? would raise an error..  I don't know what would cause that.

**Comment by jimtng** [comment]
I think because items is a set of item objects, the default `include?` is expecting an object to compare to, not a string / name of the object?
