### ISSUE TITLE
Item tags are available

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#109]
Whilst researching into persistence, I noticed that items already has tags methods.

```
    DimmerItem1.tags.each do |tag|
      logger.info("TAG: #{tag}  ")
    end
```

There's add_tags, add_tag, get_tag, remove_tag, remove_all_tags, has_tag?

It seems that it's just a matter of documenting it?

**Comment by boc-tothefuture** [comment]
I didn't add it, so it is just on the base object then?

**Comment by jimtng** [comment]
> I didn't add it, so it is just on the base object then?

Yes it appears to be the case.

**Comment by boc-tothefuture** [comment]
> 
> There's add_tags, add_tag, get_tag, remove_tag, remove_all_tags, has_tag?
> 
> It seems that it's just a matter of documenting it?

And testing in case we change how we handle items in the future.
