### ISSUE TITLE
Cucumber broken?

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#112]
It seems that cucumber currently won't run (stuck at something). It only started recently. It works fine when I am checking out an older branch that I'm working on.

**Comment by boc-tothefuture** [comment]
Locally or in the CI?
Can you share any output.  Seems to be working locally and in the CI for me.

**Comment by jimtng** [comment]
It's not working for me locally.
I then tried to wipe out my openhab install
```
$ rm -rf tmp/openhab
$ bundle openhab:setup
Could not find command "openhab:setup".
```

I re-ran bundler install several times but `bundle openhab:setup` kept saying "Could not find command openhab:setup"

Sorry I'm unfamiliar with bundle

**Comment by boc-tothefuture** [comment]
no worries.  
try this:
`bundle exec rake clean clobber openhab:setup`

**Comment by jimtng** [comment]
I followed the instructions here https://boc-tothefuture.github.io/openhab-jruby/contributing/ it says `bundle openhab:setup` - it missed the `exec` part.

> `bundle exec rake clean clobber openhab:setup`

This did the trick - partially. It failed to create users
```
$ bundle exec rake clean clobber openhab:setup
mkdir -p tmp/openhab
mkdir -p tmp/openhab/rake_state
Downloading openhab-3.0.0.zip
[0dcbb71c] Running unzip openhab-3.0.0.zip
[0dcbb71c] Finished in 0.812 seconds with exit status 0 (successful)
rm openhab-3.0.0.zip
touch tmp/openhab/rake_state/openhab_download
Starting OpenHAB
Waiting for up to 20 seconds for OpenHAB to startstart: Redirecting Karaf output to /Users/jimmy/Projects/openhab-jruby/tmp/karaf.log
....
[17156d16] Running tmp/openhab/runtime/bin/status
[17156d16] Finished in 0.726 seconds with exit status 0 (successful)
Waiting for up to 20 seconds for OpenHAB to become ready.
[1b0bd2c4] Running tmp/openhab/runtime/bin/client -p habopen 'system:version'
[1b0bd2c4] Finished in 1.260 second with exit status 0 (successful)
OpenHAB started and ready
[dc6041d2] Running tmp/openhab/runtime/bin/client -p habopen 'log:set TRACE jsr223'
[dc6041d2] Finished in 1.251 second with exit status 0 (successful)
[290f53f7] Running tmp/openhab/runtime/bin/client -p habopen 'log:set TRACE org.openhab.core.automation'
[290f53f7] Finished in 1.204 second with exit status 0 (successful)
[f7bef576] Running tmp/openhab/runtime/bin/client -p habopen 'log:set TRACE org.openhab.binding.jrubyscripting'
[f7bef576] Finished in 1.190 second with exit status 0 (successful)
[1a5d023c] Running tmp/openhab/runtime/bin/client -p habopen 'openhab:users add foo foo administrator'
[1a5d023c]      Command not found: openhab:users
[1a5d023c] Finished in 1.177 second with exit status 1 (failed)
rake aborted!
TTY::Command::ExitError: Running `tmp/openhab/runtime/bin/client -p habopen 'openhab:users add foo foo administrator'` failed with
  exit status: 1
  stdout: Command not found: openhab:users
  stderr: Nothing written
/Users/jimmy/Projects/openhab-jruby/Rakefile:155:in `fail_on_error'
/Users/jimmy/Projects/openhab-jruby/Rakefile:160:in `karaf'
/Users/jimmy/Projects/openhab-jruby/Rakefile:268:in `block (3 levels) in <top (required)>'
/Users/jimmy/Projects/openhab-jruby/Rakefile:194:in `state'
/Users/jimmy/Projects/openhab-jruby/Rakefile:263:in `block (2 levels) in <top (required)>'
/Users/jimmy/.rbenv/versions/2.5.8/bin/bundle:23:in `load'
/Users/jimmy/.rbenv/versions/2.5.8/bin/bundle:23:in `<main>'
Tasks: TOP => openhab:setup => openhab:prepare => openhab:configure
(See full trace by running task with --trace)
```

So I re-ran openhab:setup
```
$ bundle exec openhab:setup
bundler: command not found: openhab:setup
Install missing gem executables with `bundle install`
```
I did `bundle install` then tried `bundle exec openhab:setup` again but the result is the same.

I noticed that it started openhab in the background. I normally start openhab manually using tmp/openhab/start.sh, and then I end up in the console, then I can do log:tail

How do you normally watch the log when it was started in the background?

**Comment by jimtng** [comment]
Oh the command is `bundle exec rake openhab:setup`

OK when it's running properly, the openhab:setup will stop openhab at the end, so indeed the way to work is to start openhab manually like I did before.

After re-running `bundle exec rake openhab:setup` it finished setting up the users, and after starting openhab, my cucumber test is working again. Thanks for the hint!

**Comment by boc-tothefuture** [comment]
Thanks.. I updated the docs to fix the command.
