### ISSUE TITLE
between should also work with dates

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#116]
for example
between '06/06'..'12/31'

**Comment by jimtng** [comment]
there's the issue of dd/mm or mm/dd

**Comment by boc-tothefuture** [comment]
I had planned to rely on LocalDate from Java to sort all the locale stuff.

Something like `LocalDate.parse('datestring', DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT)))`

We would need to automatically add the year, and advance the year (like we do with time) if the end month/date combo is before the start month/date combo.  

It will probably be more complex than that, but that was as far as I got.

**Comment by jimtng** [comment]
So if my locale is dd/mm/yy and my code is `between '02/01'..'02/03'` and you copy pasted that code to your system whose date format is mm/dd/yy, it would not run as expected.

**Comment by boc-tothefuture** [comment]
It certainly would break - but that is the issue with locale specific dates in general, right?  But there is no other way of supporting locale specific elements that I know if.

**Comment by jimtng** [comment]
between '06Jun'..'31Dec'
between 'Jun06'..'Dec31'

At least there's no ambiguity, we can support both 06Jun and Jun06 and they can even be mixed like
between '06Jun'..'Dec31'

**Comment by boc-tothefuture** [comment]
That could work too.  Another option is what we do for TimeOfDay, where you can have a constructor that accepts H/M/S as named parameters if there is a need to be portable across locals.

**Comment by boc-tothefuture** [comment]
Getting ready to start working on this as I need it for a set of rules I am converting.. 
@jimtng anything changed in your PoV since Feb 3rd?

**Comment by jimtng** [comment]
As long as it supports month names e.g. "6 Jun" "6-Jun" "6 June" "6Jun" "Jun6" I'm happy.
