### ISSUE TITLE
Cucumber test failed but rule remains active

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#119]
I wrote a cucumber test as such:
```
  Scenario: Using invalid durations
    Given a rule
      """
      rule 'Every test' do
        every 2.seconds
        run { logger.info "Rule #{name} executed" }
      end
      """
    When I deploy the rule
    Then It should not log 'Rule Every test executed' within 70 seconds
```

Please ignore the logic for a moment. 

When "Then it should not...." failed, the cucumber test will raise an exception. After that however, this rule keeps running every 2 seconds. There's no rule file on the file system, I checked. However this rule still shows up in the console when I typed:

> automation listrules

I tried stopping openhab, then re-starting it - strangely that rule still executes.

The only way other than wiping openhab and reinstalling is to do this:

```
automation enablerule <ruleid> false
```

After that, the rule seems to vanish.

Bizarre. Slightly annoying but I put up with it.

**Comment by boc-tothefuture** [comment]
Are you sure it wasn't on the file system?  That seems odd.  Cucumber doesn't clear the rules on failure so I am not sure why it would not exist on the file system.  

Maybe you are running into #115 which I just opened today

**Comment by jimtng** [comment]
#115 is about timers that were created by the jruby helper library. The rule above creates a cron trigger, not a timer. Also, the rule itself stays active.

I've just tested it again, this time I noticed that the rule file is still there, and when I deleted that rule file, the rule was removed and was no longer running.

So I guess we just need to ensure a proper clean up at the end of the cucumber test, whether the test failed or succeeded.

**Comment by boc-tothefuture** [comment]
After a failed test, I keep the rule file in there so it can be looked at to help diagnose why the test failed.  The next test or a restart of a test does wipe it out before the test starts.
