### ISSUE TITLE
Support received_update

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#12]
Hi, I noticed you've got received_command. Would you mind adding received_update too please?

Thank you!

**Comment by boc-tothefuture** [comment]
Hi @jimtng.  Right now it supports 'updated'.  There is also an open issue to support the full text processing of the DSL rules so you could to "Item <blah> received update".  Would those two items cover this issue?

**Comment by jimtng** [comment]
Thanks. Sorry I didn't know about `updated`. That should do the trick, no need for received_update in that case.
