### ISSUE TITLE
Cucumber test for expected error

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#120]
I am trying to write a test scenario where an error is expected to happen.

This is my test scenario:
```
Scenario: Using invalid durations
    Given a rule
      """
      rule 'Invalid duration' do
        every 65.seconds
        run { logger.info "Rule #{name} executed" }
      end

      rule 'dummy' do
        on_start
        run { logger.info('dummy rule executed') }
      end
      """
    When I deploy the rule
    Then It should not log 'dummy rule executed' within 5 seconds
```

When `every 65.seconds` raised an exception, it means it's working as intended, because it cannot be translated into a cron expression (AFAIK). So the second rule 'dummy' should not have been created.

However, as it is, the cucumber test will detect the exception in the log and treat it as a failure.

Is there a way around it? Or perhaps approach the test in a different way?

**Comment by boc-tothefuture** [comment]
```
begin
  rule 'foo' do
    every 65.seconds
    run { logger.info "Should not get called" }
  end
Rescue ExceptionTypeYouWantToDetect
  logger.info "Received Expected Exception"
End
```
...
Then it should log "Received Expected Exception"

**Comment by boc-tothefuture** [comment]
@jimtng I added discussions:  https://github.com/boc-tothefuture/openhab-jruby/discussions

Should we give that a try for things like this that are not issues, but discussions and how/tos?

**Comment by jimtng** [comment]
Thanks for the tip and for the discussion area.
