### ISSUE TITLE
Comparison between NumberItem and Float doesn't work

### ISSUE THREAD

**Issue by pacive** [boc-tothefuture/openhab-jruby#121]
When trying to do a comparison between a number item and a float literal, e.g.
```ruby
if Sun_Position_Azimuth > 212.5
```
the rule fails to load with an error:
```
org.jruby.embed.EvalFailedException: (ArgumentError) can't omit precision for a Float.
```
I tracked this down to `lib/openhab/core/dsl/items/number_item.rb` and the conversion to `BigDecimal` for `Numeric` types, which fails for `Floats`.

This could be solved either by adding
```ruby
            when Float
              @number_item.state.to_big_decimal.to_f <=> other
```
Before the `when Numeric` expression in the `<=>(other)` method, or changing it to:
```ruby
            when Numeric
              @number_item.state.to_big_decimal.to_d <=> BigDecimal(other.to_s)
```
Which solution would be preferable? I'll create a PR with a fix ASAP!

**Comment by jimtng** [comment]
This would be a welcome improvement. Currently I just do NumberItem.to_i (or to_f?) and do the comparison but ideally it should be NumberItem > NN.NN as you proposed.

Related: #30 and #58 

I suppose when the conversion away from monkey patching is done, this can all be migrated across.

As to which is preferred, personally I'd avoid converting to string and back.

**Comment by jimtng** [comment]
If we were to monkeypatch the DecimalType to do the comparison, wouldn't we then just compare the state of any *Item (NumberItem, DimmerItem)?

**Comment by pacive** [comment]
I solved it in my rule by using `to_f` on the item, but thought it would be better if it can work consistently for all number types. I'll create a PR!

**Comment by pacive** [comment]
This is a problem when doing calculations with `NumberItem`s and `Float`s as well, but here the solution is not as straight-forward. It would be required to change the math operator methods (which is quite simple) and the `coerce` method. The latter creates a `Quantity` object if the item has a dimension, and the Quantity also uses `BigDecimal(numeric)` which is where the issue lies. Another solution I discovered when researching is to `require 'bigdecimal/util` which adds a `#to_d` method to the Numeric types and `String`. Would that be a better solution?

**Comment by boc-tothefuture** [comment]
@pacive - I am not following the second suggestions.. the 'bigdecimal/util'.  Can you give an example of what that would enable?

**Comment by pacive** [comment]
`bigdecimal/util` monkeypatches the `Float`, `Integer`, `Rational`, `String` and even `NilClass` classes, adding a `#to_d` method that converts them to BigDecimal, see [here](https://ruby-doc.org/stdlib-2.7.2/libdoc/bigdecimal/rdoc/Float.html) for example. The problem with Floats is that to convert them to BigDecimal using the `BigDecimal(value)` method you need to pass a second argument specifying the precision to use. The `#to_d` method doesn't have that requirement, meaning it can work the same way for all the Numeric types, so we wouldn't need any special handling for Floats

**Comment by boc-tothefuture** [comment]
That sounds good to me.  
In our code we would then just check if it `respond_to? :to_d` ? 
Go for it.  Add it to monkey_path/ruby.rb
