### ISSUE TITLE
new file not deployed to the dev environment

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#133]
I created a new file inside openhab/core/dsl/monkey_patch/types/ but when running `bundle exec cucumber features/xxxx.feature` this new file didn't get copied into the `tmp/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-2.14.1/lib/openhab/......`

As a result, my test failed

**Comment by jimtng** [comment]
It seems that I needed to commit the new file to git first because the process involves creating a new gem and deploying it locally, and the gem creation process gets the files using `git ls-files`

**Comment by pacive** [comment]
Commit is not necessary, just git add <file>. Had to learn this the hard way as well

**Comment by boc-tothefuture** [comment]
That is the default for the Gemspec - If there is a better way let's use it.

**Comment by jimtng** [comment]
It seems to be a good solution. Now that I know how to work with it, leave it be for now.
