### ISSUE TITLE
Docs:  Create a usage overview / translation doc

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#157]
I removed the initial posting from the forum that contained examples of the JRuby library because they were out of date.   @jimtng noted that they were helpful and what made him explore the library to begin with.

I think we might want to create a somewhat short markdown in the docs that has a couple of good examples of usage.  Once we have that I can update the original posting with those examples.

**Comment by jimtng** [comment]
Also I liked the outline of reasoning which is currently listed in the "Motivation" section of the docs.

**Comment by boc-tothefuture** [comment]
Ok, so have the motivation section.

Anyone have suggestions for things that should be in a new basic usage doc?

**Comment by jimtng** [comment]
Some contrived examples:

```ruby
require 'openhab'

rule 'Turn on light when door is opened' do
  changed Door_Sensor, to: OPEN
  run { Cupboard_Light.on } # Send the ON command to the item
end

rule 'Turn off light when door is closed' do
  changed Door_Sensor, to: CLOSED
  run { Cupboard_Light << OFF } # Commands can be sent using << operator too
end

# Combine the two rules above into one:
rule 'Control light based on door state' do
  changed Door_Sensor, to: [OPEN, CLOSED]
  run { Cupboard_Light << (Door_Sensor.open? ? ON : OFF) }
end

#Alternative version using the attachment feature:
rule 'Control light based on door state' do
  changed Door_Sensor, to: OPEN, attach: ON
  changed Door_Sensor, to: CLOSED, attach: ON
  run { |event| Cupboard_Light << event.attachment }
end

# Rule based on channel triggers
rule 'Turn on flood light at night' do
  channel 'astro:sun:home:set#event', attach: ON
  channel 'astro:sun:home:rise#event', attach: OFF
  run { |event| Flood_Light << event.attachment }
end  

# Rule based on group members
# Item names: LivingRoom_TV (member of TVGroup), LivingRoom_Light
rule 'Turn Off light when TV is on' do
  changed TVGroup.members, to: ON
  run do |event|
    tv_name = event.item.name # event.item is the triggering item
    light_name = tv_name.gsub('_TV', '_Light') # Change the string 'LivingRoom_TV' to 'LivingRoom_Light'
    light = items[light_name] # get the openhab item object
    light&.on # Use safe navigation operator in case light is nil
    # the previous 4 lines can be shortened to
    # items[event.item.name.gsub('_TV', '_Light')]&.on
  end
end

# Use timers
rule 'timer' do
  changed Watering_System, to: ON
  run do
    after(5.minutes) { Watering_System.off }
  end
end

# Alternatively, use a built in timer feature
rule 'timer2' do
  changed Watering_System, to: ON, for: 5.minutes
  run { Watering_System.off }
end

# Rescheduling timers, the traditional way
@timer = nil

rule 'timer3' do
  updated Motion_Sensor, to: OPEN
  run do
    Light_Item.on
    if (@timer.nil?)
      @timer = after(5.minutes) { Light_Item.off } # This is the equivalent of createTimer() in rulesdsl
    else
      @timer.reschedule # This automatically reschedules it for 5 minutes (the original duration)
      # To reschedule it a different duration, use @timer.reschedule 10.minutes
    end
  end
end

# Or use the timer "reentrant" feature to achieve the same thing
rule 'timer4' do
  updated Motion_Sensor, to: OPEN
  run do
    Light_Item.on
    # Using a unique ID, this timer automatically reschedules when called again before 5 mins is up
    after(5.minutes, id: Motion_Sensor) { Light_Item.off } 
  end
end
```

**Comment by ccutrer** [comment]
```# Use timers
rule 'timer' do
  changed Watering_System, to: ON
  run do
    after(5.minutes) { Watering_System.off }
  end
end

# Alternatively, use a built in timer feature
rule 'timer2' do
  changed Watering_System, to: ON, for: 5.minutes
  run { Watering_System.off }
end```

Note that the two are _not_ equivalent. The first one will turn off the water system 5 minutes after it turns on... every time it turns on. The second will turn off the water system after it has been continuously on for 5 minutes. The difference being if it turns on and off within 5 minutes outside the control of these rules.

**Comment by jimtng** [comment]
> Note that the two are _not_ equivalent. The first one will turn off the water system 5 minutes after it turns on... every time it turns on. The second will turn off the water system after it has been continuously on for 5 minutes. The difference being if it turns on and off within 5 minutes outside the control of these rules.

That's true! I'll remove one or the other.

Organise by "feature" with hidden/reveal sections "faq style"
Topics:
* Referring to item's name
* Getting an item from a name/string
* logging
* add examples for `cron` and `every`, timeofday, monthday, range
* changed for (changed duration)
* received_command, event.command
* Multiple commands
* thing trigger
* channel trigger
* multiple items
* multiple triggers
* groups
* group members, triggeringItem (run:event.item / triggered:item)
* event.state / event.was
* guards only_if/not_if
* terse rules
* timers examples, N.seconds to create duration, rescheduling with default duration
* metadata
* persistence
* accessing things, thing status
* actions: send email, publish mqtt, exec, sound, `say` (tts)
* number item calculations
* demonstrate UoM calculations / automatic unit conversion
* convert numbers to quantitytype with `|`

The idea is to give people a "one page overview" of all the capabilities by looking at example codes (with some descriptive comments) instead of poring through the various sections of the docs.

**Comment by jimtng** [comment]
Note: add a "Ruby Crash Course" section.
* People who came from Openhab looking for a scripting language, like myself when I first came across this library, might not know anything about ruby
* Include just the basics to get them started writing rules: if/elsif, case/when, array, hash, some basic loops, next/break/return, parentheses vs no parentheses.
* Provide useful external links for more info

**Comment by jimtng** [comment]
I think between the #554, #555, and  #567 this issue is resolved.

The only other thing I can think of is to add more "Conversions" which can come from 
https://community.openhab.org/t/openhab-jruby-rule-conversation/127380
