### ISSUE TITLE
Metadata syntax - safe navigation to access the configuration

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#158]
Currently when the metadata namespace doesn't exist, `Item.meta['nonexistent']` would return nil. Is there a way to do some sort of safe navigation to access the metadata config on a non existent metadata, i.e. (I know this syntax is wrong but it should demonstrate the intention) `Item.meta['nonexistent']&['namespace_config']`

Currently it can be done like this `Item.meta['nonexistent']['namespace_config'] unless Item.meta['nonexistent'].nil?` which is not very nice.

Maybe we can do it like this (which is yet to be implemented): `Item.meta['nonexistent']&.config['namespace_config']`

What's the Ruby way of doing this?

**Comment by pacive** [comment]
Not sure if it's implemented, but in a regular Hash, `#dig`would be the way to go: https://ruby-doc.org/core-2.5.8/Hash.html#method-i-dig

**Comment by pacive** [comment]
It wasn't available at the top level, so I added it. If it gets merged you could do:
```ruby
Item.meta.dig('nonexistent', 'namespace_config)
```
and just get nil back regardless of where it fails.
