### ISSUE TITLE
complex timer interactions

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#16]
How can I control timers from other rules? It currently seems impossible using the `after` method or using the `for` condition 

Scenario:
Items: `Light`, `ExhaustFan`, `Motion_Sensor`

* When `Light` is turned on, I want it to automatically turn off after 15 minutes, but only if the `ExhaustFan` is not running, and no motion was detected in the past 10 minutes
* When the `ExhaustFan` turns off, wait for 10 minutes before turning off `Light`. So if the `ExhaustFan` turns off, then 3 minutes after it turns back on, it won't turn off `Light`.
* When motion is detected, schedule to turn off `Light` (if on) in 10 minutes, but only if `ExhaustFan` is off

**Comment by boc-tothefuture** [comment]
Hi @jimtng - 
Some of these might be better to paste in the forum?  Just so more people can weigh in.

But let me understand each case here so I understand the ask.  I am writing the rules below without testing them, so the syntax may be slightly off..

> When the ExhaustFan turns off, wait for 10 minutes before turning off Light. So if the ExhaustFan turns off, then 3 minutes after it turns back on, it won't turn off Light.

```
 rule 'Turn off light after Exhaust fan off for 10 minutes' do
  changed ExhaustFan to: OFF, for 10.minutes
  run { Light.off if Light.on? } 
end
```
That will turn the light off 10 minutes after the exhaust fan is switched off.  If the exhaust fan is switch on after say 3 minutes, the internal timer will be cancelled.  Once its turned off again the internal timer will start for 10 minutes. 


> When motion is detected, schedule to turn off Light (if on) in 10 minutes, but only if ExhaustFan is off

Does this mean you want the light to turn off in 10 minutes if the fan is off in 10 minutes?  Or to not even schedule it turn off if the fan is on? 

if it is the later:

```
rule 'Turn off light after 10 minutes if exhaust fan is off' do
  changed Motion_Sensor to: ON
  run do 
      after 10.minutes { Light.off }  if ExhaustFan.off? 
 end  
end
```

After blocks in rules are not currently reentrant (they don't self cancel and reset inside of run blocks).  So this will create a new timer every time the sensor is triggered.. I am assuming you don't want that behavior?  We can work around that using things similar to other rule engine designs (assign the result of timer to a variable that you check).  But I would like to abstract that away..  so let me know if your use case is rentrant. 

> When Light is turned on, I want it to automatically turn off after 15 minutes, but only if the ExhaustFan is not running, and no motion was detected in the past 10 minutes

Do you have the code for this in either the python DSL or the built in rules DSL? 

There are a couple of ways to handle this with the constructs that currently exist.

**Comment by jimtng** [comment]
This is my code so far, using a global variable. Bear in mind I have only started looking at Ruby for about 2 days, so please forgive any mistakes, but I hope you can understand what I'm trying to achieve

```ruby
require 'openhab'

$timer = nil

rule 'Rule1 Bathtub Light autooff' do
    changed BathTub_Light, to: ON
    run do
        $timer = after 15.minutes do |timer|
            if BathTub_Light.on?
                if MasterBathRoom_ExhaustFan.on? 
                    timer.reschedule
                else
                    BathTub_Light.off 
                end
            end
        end
    end
end

rule 'Rule2 Bathtub light turned off' do
    changed BathTub_Light, to: OFF
    run do
        if $timer 
            $timer.cancel if $timer.isActive
            $timer = nil
        end
    end
end

rule 'Rule3 Bathtub Light turn off with exhaust fan' do
    changed MasterBathRoom_ExhaustFan, to: OFF
    run { $timer.reschedule if $timer and BathTub_Light.on? }
end

rule 'Rule4 BathTub Motion detected' do
    changed [MasterBedRoom_Motion, MasterBathRoom_Motion], to: OPEN
    run { $timer.reschedule if $timer and BathTub_Light.on? }
end
```

**Comment by jimtng** [comment]
To make the timer "reentrant" i.e. to avoid multiple timers being created if for some reason the BathTub_Light changed to ON multiple times (e.g. it became NULL and ON again)

```ruby
rule 'Rule1 Bathtub Light autooff' do
    changed BathTub_Light, to: ON
    run do
        if $timer and $timer.isActive
            $timer.cancel
        end
        $timer = after 15.minutes do |timer|
            if BathTub_Light.on?
                if MasterBathRoom_ExhaustFan.on? 
                    timer.reschedule
                else
                    BathTub_Light.off 
                end
            end
        end
    end
end
```

I'd love to see a more elegant way of doing this.

**Comment by boc-tothefuture** [comment]
Yes.. that is really kind of messy right now and the after syntax wasn't created with multiple rules interacting in mind..

I will need to think for a bit about how we could clean this up so it is intuitive.  

Using a bit of a different approach and some ruby constructs I think we can make what you have now a bit more palatable.  When I get a bit to play with it I will post something for feedback.

**Comment by jimtng** [comment]
The next common thing I do is having a hash of timers to keep track of multiple timers (e.g. one for each item within the same rule, or for completely different rules).

Here's what the above rules have evolved to in order to work for multiple lights. Each light has different other items (exhaust fans, motion sensors) that can influence it. I am sure this is embarrassingly too complicated and can be simplified.

```ruby
require 'openhab'

$timers = {}

LIGHTS = { 
    "BathTub_Light" => [ "MasterBathRoom_ExhaustFan", "MasterBedRoom_Motion", "MasterBathRoom_Motion" ],
    "MainBathRoom_Light_Power" => [ "MainBathRoom_ExhaustFan", "MainBathRoom_Motion" ]
}

# CHECK_ITEMS should contain all the values of LIGHTS in a flattened array, i.e.
# [ "MasterBathRoom_ExhaustFan", "MasterBedRoom_Motion", "MasterBathRoom_Motion", 
#   "MainBathRoom_ExhaustFan", "MainBathRoom_Motion" ]
CHECK_ITEMS = LIGHTS.values.flatten

# LIGHT_ITEMS should contain items: BathTub_Light and MainBathRoom_Light_Power
# LIGHT_ITEMS = items.select { |item| LIGHTS.key?(item.name) }
LIGHT_ITEMS = LIGHTS.keys.collect {|i| items[i]}

rule 'Rule1 Shower Light autooff in 15 mins unless exhaust fan is running' do
    changed LIGHT_ITEMS, to: ON
    triggered do |item|
        if $timers[item.name] and $timers[item.name].isActive
            $timers[item.name].cancel
        end
        $timers[item.name] = after 10.minutes do |timer|
            if !item.on?
                return
            end

            check_items = LIGHTS[item.name]
            turn_off = true
            for check_item in check_items do
                if items[check_item].is_a? Switch and items[check_item].on?
                    timer.reschedule
                    turn_off = false
                    break
                end
            end
            if turn_off
                logger.info("RUBY turning off #{item.name} from timer")
                item.off 
            end
        end
        logger.info("RUBY created a timer called #{item.name}")
    end
end

rule 'Rule2 Shower light turned off -> disable timer' do
    changed LIGHT_ITEMS, to: OFF
    triggered do |item|
        if $timers[item.name]
            $timers[item.name].cancel if $timers[item.name].isActive
            $timers.delete(item.name)
            logger.info("RUBY cancelled timer for #{item.name}")
        end
    end
end

rule 'Rule3 Shower Light delay turning off when motion is detected or exhaust fan just turned off' do
    changed CHECK_ITEMS.collect { |i| items[i] }, to: [ OFF, OPEN ]
    triggered do |item| 
        logger.info("RUBY #{item.name} is #{item.state}")
        light_name = LIGHTS.find { |k,v| v.include?(item.name) }.first
        if $timers[light_name] and items[light_name].on?
            $timers[light_name].reschedule 
            logger.info("Item: #{item.name} extended the timer #{light_name}")
        end
    end
end
```

Notable things that I had struggled with, being very new with Ruby and all:
* Get a list of items for the `changed` condition, given a string array of item names.
```ruby
CHECK_ITEMS = [ "LightItem1", "LightItem2" ]
CHECK_ITEMS.collect { |i| items[i] } #CHECK_ITEMS is the string array of item names I want to extract out of `items`
```
 It would be great if there's a way to simplify this, e.g. `items[ ["Item1", "Item2"] ]` i.e. the items[] syntax accepting an array of strings instead of just a single string, in order to return multiple items.

* I'd just like to say I love being able to do this: `to: [ OFF, OPEN ]`. This has allowed me to combine two rules into one.

**Comment by boc-tothefuture** [comment]
I haven't tested this, so I can't promise it works.  It is also only maybe a slight improvement to your original.
```
def bathtub_timer
  @bathtub_timer ||= Timer.new(duration: 15.minutes) do |timer|
    if BathTub_Light.on? && MasterBathRoom_ExhaustFan.on? 
      timer.reschedule
    elsif BathTub_Light.on?
      BathTub_Light.off 
      @bathtub_timer = nil
    else 
      @bathtub_timer = nil
    end
  end
end

rule 'Bathtub Light Auto-Off' do
  changed BathTub_Light
  run do |event|
    case event.state
    when ON then bathtub_timer.reschedule
    when OFF 
      @bathtub_timer&.cancel
      @bathtub_timer = nil
  end
end

rule 'Reset Bathtub Timer' do
  changed MasterBathRoom_ExhaustFan, to: OFF
  changed [MasterBedRoom_Motion, MasterBathRoom_Motion], to: OPEN
  run { @bathtub_timer&.reschedule }
  only_if BathTub_Light
end
```
It moves the timer to an instance variable instead of a global.  Unless you need that timer accessible from multiple rules files I would try and avoid the global if at all possible.

It moves the creation of the timer to a method and uses the ruby ||= syntax to automatically create an object if the object you are setting it to is nil.  

Additionally, it uses the safe navigation operator `&.` to skip/automatically apply the if $timer checks that were in the code. In other words, if the object is nil, it won't run the method. 

It still isn't great.

**Comment by boc-tothefuture** [comment]
A few tips below if you wanted some alternate methods of tackling these problems. 

> ```
> # a mapping of lights => other items that control the light
> LIGHTS = { 
>     "BathTub_Light" => [ "MasterBathRoom_ExhaustFan", "MasterBedRoom_Motion", "MasterBathRoom_Motion" ],
>     "MainBathRoom_Light_Power" => [ "MainBathRoom_ExhaustFan", "MainBathRoom_Motion" ]
> }
> 
> # CONTROL_ITEMS is a list of items that consists of all the values in the LIGHTS hash above, i.e.
> # item["MasterBathRoom_ExhaustFan"], item["MasterBedRoom_Motion"], item["MasterBathRoom_Motion"], 
> # item["MainBathRoom_ExhaustFan"], item["MainBathRoom_Motion"]
> CONTROL_ITEMS = LIGHTS.values.flatten.collect { |i| items[i] }
> 
> # LIGHT_ITEMS should contain items: BathTub_Light and MainBathRoom_Light_Power
> # LIGHT_ITEMS = items.select { |item| LIGHTS.key?(item.name) }
> LIGHT_ITEMS = LIGHTS.keys.collect {|i| items[i]}
> 
> ```

You don't have to use strings for your mapping, you can use the items themselves. 
e.g. lights = { 
   Bathtub_Light => [ MasterBathroom_ExhaustFan ]
}

light_items = lights.keys
control_items = lights.values.flatten

> `$timers[item.name].cancel if $timers[item.name] and $timers[item.name].isActive`

Should in almost all cases used && instead of and.  

`$timers[item.name]&.cancel`
You can use the safe navigation operator to avoid the if check, also I don't think there is any harm in canceling a timer that isn't active. 

`light_name = LIGHTS.find { |k,v| v.include?(item.name) }.first`
Assuming you put objects instead of strings (or even if you don't), this should work:
`light = LIGHTS.invert[item]`

**Comment by boc-tothefuture** [comment]
> Notable things that I had struggled with, being very new with Ruby and all:
> 
> Get a list of items for the changed condition, given a string array of item names.
> CHECK_ITEMS = [ "LightItem1", "LightItem2" ]
> CHECK_ITEMS.collect { |i| items[i] } #CHECK_ITEMS is the string array of item names I want to extract out of `items`
> It would be great if there's a way to simplify this, e.g. items[ ["Item1", "Item2"] ] i.e. the items[] syntax accepting an array of strings instead of just a single string, in order to return multiple items.


I think I mentioned this above, but you don't need to use strings you can refer to the items directly - this is different than the Jython syntax. Does that help?

FYI.. Collect works fine for what you are doing - in ruby you would usually use the `map` method instead just as a way of saying, 'I have these objects, and I am going to map them to a different type, one for one'.  Collect works, but map is the standard idiom I have seen in the wild.

> 
> I'd just like to say I love being able to do this: to: [ OFF, OPEN ]. This has allowed me to combine two rules into one.

What happens if you do that?  Does the underlying openhab engine throw an error? 

You should still be able to have a single rule anyway

```
rule 'do things with different types' do
  changed control_items.grep(Contact), to: OPEN
  changed control_items.grep(Switch), to: OFF
end
```

**Comment by jimtng** [comment]
>>I'd just like to say I love being able to do this: to: [ OFF, OPEN ]. This has allowed me to combine two rules into one.

> What happens if you do that? Does the underlying openhab engine throw an error?

It seems to work fine

**Comment by jimtng** [comment]
I was wondering, can we attach / add a timer object to an item as its property?

What I mean was this:

```ruby
rule 'Rule1' do
    changed SomeItem, to: ON
    triggered do |item|
        item.timer?.cancel
        item.timer = after 10.minutes do |timer|
           #do something in the timer
        end
    end
end

rule 'Rule2' do
  changed OtherItem, to: ON
  triggered do |item|
    SomeItem.timer.reschedule
  end
end
```

It only covers the scenario where a timer is associated with an item, and limits things a bit, i.e. only one timer per item, etc. For a specific case, it works well, but not for others.

Is this sort of thing (adding an extra property to an arbitrary object) easy to do with Ruby though? Because if it's easy enough, it might be worth adding to our bag of tricks.

**Comment by jimtng** [comment]
Continued on #315
