### ISSUE TITLE
gems.locked file

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#160]
I noticed the file gems.locked. Should this be included in .gitignore?

**Comment by boc-tothefuture** [comment]
Gemfile.lock?

I don't seem to have a gems.locked

**Comment by jimtng** [comment]
File lib/openhab/dsl/gems.locked

```
GEM
  specs:

PLATFORMS
  x86_64-darwin-19

DEPENDENCIES

BUNDLED WITH
   2.2.7
```

**Comment by boc-tothefuture** [comment]
I don't have that and I don't see it in the main branch.

**Comment by jimtng** [comment]
Something is generating it on my system every time I saved an .rb file, and it's always in lib/openhab/dsl/gems.locked
I think it's one of vscode's extensions. I narrowed it down to these lines in my settings.json:

```
    "ruby.lint": {
         "rubocop": {
             "useBundler": true
         }
     },
```
When commented out, the gems.locked file stopped appearing.
