### ISSUE TITLE
Log Script/JRuby errors

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#17]
Right now they go to stdout.. investigate if they can go to the log instead.

**Comment by jimtng** [comment]
It would be good if we don't have to set the log level to DEBUG on org.openhab.core.automation. DEBUG adds a lot of extra information that could be distracting.
Jython doesn't require DEBUG on this to see detailed script errors.

**Comment by boc-tothefuture** [comment]
I will have to look at that because the setting is in the core.  I would think it would be better for the core to log these problems at error level rather than debug.  I am not sure the best approach is each language working around it.

I will take a look

**Comment by boc-tothefuture** [comment]
After chatting with the JRuby developers, I opened an [issue](https://github.com/jruby/jruby/issues/6560)

**Comment by jimtng** [comment]
Yes by default, Jython logs the line number albeit not too accurately, as I demonstrated in https://github.com/jruby/jruby/issues/6560#issuecomment-781822268

Jython helper libraries, does something extra to include the stack trace by decorating the rule with this:
https://github.com/openhab-scripters/openhab-helper-libraries/blob/master/Core/automation/lib/python/core/log.py

**Comment by jimtng** [comment]
Thanks @pacive this works beautifully and it is very helpful to have the stack trace so informative.
