### ISSUE TITLE
Event states need to be decorated

### ISSUE THREAD

**Issue by pacive** [boc-tothefuture/openhab-jruby#176]
Currently this rule fails:
```ruby
rule 'Windwarnings' do
  updated SMHI_Hour0_WindSpeed
  run do |event|
    wind = event.item_state
    Hard_Wind_Expected.update(wind >= 13 ? ON : OFF)
    Storm_Expected.update(wind > 24 ? ON : OFF)
  end
end
```
if `event.item_state` is a QuantityType, because it cannot be compared (DecimalTypes seems to work though). To make it work it needs to be wrapped as a `OpenHAB::DSL::Types::Quantity`
I get the same result even if I use `event.item.state`.

**Comment by jimtng** [comment]
also `event.last` (for changed triggers)
`event.item` is decorated, so `event.item.state` should be whatever we have on the general `item.state`.

We have our own `Quantity` class (not `QuantityType`), whereas we only monkey patch DecimalType which is why it's working. It is a bit confusing.

**Comment by pacive** [comment]
Yeah, noticed that when digging into the code a bit further. There is also a monkey patch for QuantityType, but it seems it doesn't support comparison to Numeric.

**Comment by pacive** [comment]
There seems to be something funky going on with `event.item.state` as well:
```
2021-02-18 12:12:29.743 [WARN ] [jsr223.jruby.Gustwarnings           ] - event.item_state: 8.8 m/s (Java::OrgOpenhabCoreLibraryTypes::QuantityType)
2021-02-18 12:12:29.748 [WARN ] [jsr223.jruby.Gustwarnings           ] - event.item: 8.8 m/s (OpenHAB::DSL::Items::NumberItem)
2021-02-18 12:12:29.755 [WARN ] [jsr223.jruby.Gustwarnings           ] - event.item.state: 8.8 m/s (Java::OrgOpenhabCoreLibraryTypes::QuantityType)
```
The Item gets wrapped correctly, but not the state.

**Comment by pacive** [comment]
Ah, comparing against `event.item` instead of `event.item.state` works as expected even with Numeric. Closing this as the solution is probably to solve #58.
