### ISSUE TITLE
Singleton on non-persistent Java type

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#189]
A warning has started to appear recently while using the library:
```
openhab-scripting-2.21.0/lib/openhab/dsl/rules/automation_rule.rb:229: warning: singleton on non-persistent Java type Java::OrgOpenhabCoreItemsEvents::ItemStateChangedEvent (http://wiki.jruby.org/Persistence)
```

**Comment by pacive** [comment]
That would be here:
```ruby
        def decorate_event_item(event)
          return if event.nil?

          class << event # <-- This line
            def item
              OpenHAB::Core::EntityLookup.lookup_item(item_name)
            end
          end
        end
```
@jimtng you wrote this method, could it be done in another way?

**Comment by jimtng** [comment]
According to https://github.com/jruby/jruby/wiki/Persistence we could add `Class.__persistent__ = true`. Need to check whether `event` is always the same class. I don't know of other ways to do this, but I'm a Ruby newbie.

**Comment by jimtng** [comment]
@boc-tothefuture where did you see this warning? Can you test below code?

I've just tried this, and it works too, but I don't know whether it triggered the same warning:
```ruby
        def decorate_event_item(event)
          return if event.nil?

          event.define_singleton_method(:item) do
            OpenHAB::Core::EntityLookup.lookup_item(item_name)
          end
        end
```

The cucumber test for this is the last one in `run.feature`

**Comment by jimtng** [comment]
Another option (also works) is to remove `decorate_event_item` completely, and monkey patch  the event classes. I'm testing this right now.

**Comment by jimtng** [comment]
After further digging, I discovered that fixing this issue creates a cleaner structure overall. Previously, I wasn't aware that the item was already created in ItemStateChangedEvent monkey patch, which we overrode in decorate_event_item. Now it just needs to be done in the parent class to cover all types of events (updated, changed, command).
