### ISSUE TITLE
send_command_if_different()

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#19]
This syntax is good, and we should keep it:
```
SwitchItem.on
```

It would also be great if we could have something similar to jython's helper send_command_if_different(). I'm not sure what would be the perfect syntax / name. Right now we can do 
```
SwitchItem.on if !SwitchItem.on?
```
Or, slightly different but not as foolproof:
```
SwitchItem.on if SwitchItem.off?
```

What I'm suggesting is something like
```
SwitchItem.on_if_not   #or....
SwitchItem.on_         #might be vague. Is there a Ruby-ish convention?
```

Also have one for postupdate.

**Comment by boc-tothefuture** [comment]
Hi @jimtng - 
  Thanks for the suggestions. 

  In general (but not always) you don't need to using the ! with an if, because you have unless. 

So:

```
SwitchItem.on if !SwitchItem.on?
```

becomes
```
SwitchItem.on unless SwitchItem.on?
```

> Or, slightly different but not as foolproof:
> 
> SwitchItem.on if SwitchItem.off?
> 

Why is this issue with that that makes it not foolproof?


> SwitchItem.on_if_not   #or....
> SwitchItem.on_         #might be vague. Is there a Ruby-ish convention?
> 

The ruby conversion is to use the 'post conditional'.  

Do we think its too long or do we think it's dangerous to send the commands when not needed?

**Comment by jimtng** [comment]
> `SwitchItem.on unless SwitchItem.on?`

I'm happy with this syntax. This achieves exactly what "send_command_if_different" does.

>> Or, slightly different but not as foolproof:
>>SwitchItem.on if SwitchItem.off?
>Why is this issue with that that makes it not foolproof?

When SwitchItem's state is NULL or UNDEFINED, I presume it then won't send the ON command

**Comment by boc-tothefuture** [comment]
> When SwitchItem's state is NULL or UNDEFINED, I presume it then won't send the ON command

That is correct.. However I am wondering if that is the right way to handle it.. 

Since you are happy with the syntax, I am going to close this issue and open another one on what off? should do for null/undef.
