### ISSUE TITLE
change all logger.trace to use block syntax

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#194]
When doing logger.trace("xxx #{method.call}"), the string will get interpolated and evaluated, hence method.call executed, regardless of the enabled logging level. We should use the block syntax logger.trace { "xxx #{method.call}" } so method.call wouldn't execute when trace level is not enabled. It may only be an infinitesimal benefit, but it is the right thing to do, IMO. This makes our logging similar to or even better than Java's string expansion syntax of `logger.trace("xxx {}", var)`

I can do a PR for this if y'all agreed

**Comment by pacive** [comment]
Good idea! Would have to alter the Logging class' method definitions, and all logging statements, so would be a rather big refactor, but the potential performance improvement can be worth it.

**Comment by jimtng** [comment]
The current implementation already supports blocks. The two things I would change are perhaps a) to remove the check for unknown severity because I cannot see how it could be passed an unknown level, and b) convert the list of the levels to lowercase, to remove the need to call downcase. It would remove a few function calls in the process.

The rest is just a matter of doing a global search/replace.

**Comment by pacive** [comment]
> The current implementation already supports blocks

Ah, hadn't noticed that! Will make sure to use it in the future. Sounds good!

**Comment by boc-tothefuture** [comment]
FYI, no idea what is more expensive - wrapping things in a block vs. string interpolation.  Creating blocks that have access to the surrounding environment is probably not free (probably not expensive either).

You would not want to replace any logging with a block that is just a string without interpolation.  

I have been just using the block when it was clear that the interpolation would be expensive.

**Comment by jimtng** [comment]
> FYI, no idea what is more expensive - wrapping things in a block vs. string interpolation.  

It's not the interpolation that I'm concerned about. It's when method calls occur within the interpolation. Sometimes there are multiple method calls in a trace string. I'm guessing that method calls would be more expensive than wrapping things in a block. Plus those method calls may issue log traces themselves. 

I agree that log traces with no interpolation, or even the ones with simple interpolation without method calls should remain as is and not converted to block calls.
