### ISSUE TITLE
Group Redesign

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#202]
Opening up this issue to discuss redesign of groups and to consolidate other threads

**Comment by boc-tothefuture** [comment]
Also it should support:

on|off|on?|off? (if it's based on Switch type)
open?|closed? (if based on Contact type)
.truthy? so that it can be used with only_if

From @jimtng in #180

**Comment by boc-tothefuture** [comment]
#185 makes item.groups to return the list of groups that the item is a member of, i.e. its ancestors.
However, Group.groups currently would return the list of its members (which is of group type), i.e. its descendants

From #201

**Comment by boc-tothefuture** [comment]
Let's use this issue to layout the group redesign.

**Comment by boc-tothefuture** [comment]
> Also it should support:
> 
> on|off|on?|off? (if it's based on Switch type)
> open?|closed? (if based on Contact type)
> .truthy? so that it can be used with only_if
> 
> From @jimtng in #180

Good ideas..  this should be much easier to support now that we item_command

truthy? would be supported based on the underlying items truthy correct? 
What do we do if only some of the items support truthy?

**Comment by pacive** [comment]
I have made a PR that I think can be used as a base for discussion.

> How do we get the type?

The accepted states and command can be gotten from the OH GroupItem and patched on the Item's singleton class, see my PR. If you know a better way I'm all ears. But would be even easier if #179 gets merged.

**Comment by boc-tothefuture** [comment]
#179 has conflicts

**Comment by pacive** [comment]
> #179 has conflicts and I thought also outstanding items to address?

Didn't notice there had been conflicts, fixed now, as well as the other items!

**Comment by jimtng** [comment]
> truthy? would be supported based on the underlying items truthy correct?
> What do we do if only some of the items support truthy?

We'll only support truthy? if the Group was defined like this:

```
Group:Switch:OR(ON,OFF)
```

It doesn't matter if some/all the members do not support truthy? It's the Group's state that matters.

I haven't checked, but my guess is that when it was defined like above, getAcceptedCommand Types will return OnOffType. So when it does return OnOffType, we can define truthy?

**Comment by jimtng** [comment]
We also need to be able to do this:

```
if Group == OPEN
or
if Group == ON
```
Which are the equivalent of Group.open? and Group.on?

**Comment by jimtng** [comment]
Ref: https://www.openhab.org/docs/configuration/items.html#derive-group-state-from-member-items
Groups can also act like DateTime and Number, so they should also be comparable to DateTime, TimeOfDay, ZonedDateTime, etc. when it's a DateTime Group, and comparable to numbers, or even quantity when it's a number.

**Comment by pacive** [comment]
> Ref: https://www.openhab.org/docs/configuration/items.html#derive-group-state-from-member-items
> Groups can also act like DateTime and Number, so they should also be comparable to DateTime, TimeOfDay, ZonedDateTime, etc. when it's a DateTime Group, and comparable to numbers, or even quantity when it's a number.

This would mostly be handled by delegating to the state, but perhaps we would need to define a `decorate_state` method somewhere so our wrapped states gets returned correctly.

**Comment by boc-tothefuture** [comment]
This also means that all of our other types (OnOffType,OpenClosedType) need to be group aware in their equals and case operators.

**Comment by pacive** [comment]
> This also means that all of our other types (OnOffType,OpenClosedType) need to be group aware in their equals and case operators.

Could this be solved with a simple `respond_to?(:state)` check? That would work for all items, right?

**Comment by jimtng** [comment]
Another criteria: Make sure it also has access to metadata and persistence, i.e. Group.meta, Group.last_update, etc.
