### ISSUE TITLE
Persistence methods that return a HistoricItem should return its state

### ISSUE THREAD

**Issue by pacive** [boc-tothefuture/openhab-jruby#208]
Most persistence methods return a DecimalType, but `maximumSince`, `minimumSince` and `historicState` returns a `HistoricItem` instead, so for these methods we need to add `.state` to the result in order for them to work correctly.

**Comment by jimtng** [comment]
I'm not sure I understand the issue. This code works for me:
```ruby
midnight = ZonedDateTime.now.withHour(0).withMinute(0).withSecond(0)
max = Solar_AC_Power.maximum_since(midnight, :influxdb)
logger.error("Max since: #{max.state}, occurred at: #{max.timestamp}")
```

**Comment by pacive** [comment]
Yes, but you have to add `.state` which makes it inconsistent with the other methods. But since this is how it's returned by OH perhaps we should let it be that way. But then I think the behaviour should be described in the docs, e.g. add a column with return types to the method table.

**Comment by boc-tothefuture** [comment]
> midnight = ZonedDateTime.now.withHour(0).withMinute(0).withSecond(0)
> max = Solar_AC_Power.maximum_since(midnight, :influxdb)

Unrelated but does our `MIDNIGHT` constant not work here? If it doesn't, seems like something we would want to address (in another issue).

**Comment by boc-tothefuture** [comment]
@pacive is it that we need to_s to defer to the state like it does for other items?

**Comment by pacive** [comment]
No, but if you want to compare with e.g a number would have to do it differently depending on which method you call:

```ruby
if Solar_AC_Power.average_since(midnight, :influxdb) > 20
```
vs
```ruby
if Solar_AC_Power.maximum_since(midnight, :influxdb).state > 20
```
Since HistoricItem is a different interface than Item, and hence not a descendant of GenericItem our extensions are not applied to it either.

**Comment by jimtng** [comment]
The point of HistoricItem is so that we could also get the timestamp when the value was saved. I guess we can make it so:
```ruby
Solar_AC_Power.maximum_since(midnight, :influxdb) # returns the state (optionally quantified)
Solar_AC_Power.maximum_since(midnight, :influxdb).timestamp # returns the timestamp

# in case someone wants to access it using .state after reading openhab's documentation 
# and not aware of the difference in our implementation
Solar_AC_Power.maximum_since(midnight, :influxdb).state 
```

**Comment by pacive** [comment]
> The point of HistoricItem is so that we could also get the timestamp when the value was saved. I guess we can make it so:
> 
> ```ruby
> Solar_AC_Power.maximum_since(midnight, :influxdb) # returns the state (optionally quantified)
> Solar_AC_Power.maximum_since(midnight, :influxdb).timestamp # returns the timestamp
> 
> # in case someone wants to access it using .state after reading openhab's documentation 
> # and not aware of the difference in our implementation
> Solar_AC_Power.maximum_since(midnight, :influxdb).state 
> ```

This would seem the best solution, so we won't have to remove any functionality. Would it be possible to make a simple wrapper by subclassing NumberItem? That would make it support all comparisons since it holds a DecimalType or QuantityType.

**Comment by jimtng** [comment]
> Would it be possible to make a simple wrapper by subclassing NumberItem?

I think DecimalType would be more appropriate here, because it isn't a separate "item". The other methods return DecimalType so it makes sense to use DecimalType to make them all uniform. I'll have a play with this.
