### ISSUE TITLE
ver 3.0 Error: stack level too deep

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#213]
When a rule specifies multiple trigger items, an error "stack level too deep" will occur.
```ruby
rule 'x' do
  changed Item1, Item2
  run { logger.info('x') }
end
```

**Comment by boc-tothefuture** [comment]
Did the group commit break this?

I am surprised we don't have a test case for this.

**Comment by jimtng** [comment]
Yes, the problem is inside `separate_groups` inside trigger.rb
I'm working on this but feel free to jump in 

It just needed one fix so far but I'm testing different scenarios.

Should this be supported:
```ruby
rule 'x' do
  changed [Item1, Item2]
end
```

**Comment by boc-tothefuture** [comment]
> 
> Should this be supported:
> 
> ```ruby
> rule 'x' do
>   changed [Item1, Item2]
> end
> ```

Yes.  

It will take a bit until I can look.
