### ISSUE TITLE
Support for Group.items << COMMAND 

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#22]
Currently it seems that 
```
Group.items << COMMAND
``
is not yet supported

**Comment by boc-tothefuture** [comment]
It should just be:

Group << COMMAND

**Comment by boc-tothefuture** [comment]
@jimtng can this be closed?

**Comment by jimtng** [comment]
Group << Command sends the command to the group, done by OpenHAB Core itself. I was thinking of Group.items << Command sending the command to each item individually, by jruby. But - perhaps there's no real difference in the end, so I'm happy to close this.
