### ISSUE TITLE
error logging undefined method `backtrace_locations'

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#220]
I was in the middle of troubleshooting an issue and created this file:

```ruby
require 'openhab'

    on_time = BackyardPlants_Watering_Tap.previous_state(:influxdb, skip_equal: true)
    logger.error(on_time.to_s)
```

The error logged was:
```
06:33:43.376 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/ruby/personal/test.rb': org.jruby.embed.EvalFailedException: java.lang.IllegalArgumentException: Cannot format given Object as a Date
```

However when I put those two lines inside a rule:
```ruby
rule 'x' do
  on_start
  run do
    on_time = BackyardPlants_Watering_Tap.previous_state(:influxdb, skip_equal: true)
    logger.error(on_time.to_s)
  end
end
```

The error being logged was:
```
06:36:30.999 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/ruby/personal/test.rb': org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `backtrace_locations' for #<Java::JavaLang::IllegalArgumentException:0x42c7c72e>
In rule: x
<script>:9:in `<main>'
```

It seems that java exceptions don't have `backtrace_locations`? I also noticed that the exception message is lost here.

**Comment by jimtng** [comment]
Maybe check for respond_to? backtrace_locations and if not available, try `stack_trace` from https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Throwable.html#getStackTrace()

It seems to give you the full trace so it's quite long and I think only the top few lines are interesting / relevant.

**Comment by pacive** [comment]
Not sure it's as easy to clean up java stack traces, but will look into it!
