### ISSUE TITLE
DateTime Item doesn't accept ZonedDateTime

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#222]
This code failed:

```ruby
DateTimeItem1 << ZonedDateTime.now
```

```
13:02:38.797 [WARN ] [ab.core.model.script.actions.BusEvent] - Cannot convert '2021-03-05T13:02:38.788380+10:00[Australia/Brisbane]' to a state type which item 'DateTimeItem1' accepts: [DateTimeType, UnDefType].
```

I understand that this is actually an openhab-core problem. Do we want to intercept and correct it?

The same error occurred with #update too

**Comment by jimtng** [comment]
This works:

```ruby
DateTimeItem1 << ZonedDateTime.now.toLocalDateTime
```

**Comment by pacive** [comment]
I think that's because of the [Australia/Brisbane] part, which cannot be parsed by DateTimeType. Would have to override the command and update methods to fix this.

**Comment by jimtng** [comment]
`org.openhab.core.library.types.DateTimeType` has a constructor accepting ZonedDateTime
`org.openhab.core.library.items.DateTimeItem.send` takes a DateTimeType as its argument.

**Comment by pacive** [comment]
Yes, but when a command is sent (via the scripting library) it calls: `BusEvent.sendCommand(self, command.to_s)`, so it doesn't create the DateTimeType from the ZonedDateTime object when OH receives it, but its string representation.

**Comment by pacive** [comment]
There is other overloaded methods in the [BusEvent](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/BusEvent.java) class, but that would mostly require that a valid Command instance is created before it's passed there, so wouldn't accept a ZoneDateTime directly either way.

**Comment by jimtng** [comment]
DateTimeType implements Command:
```
public class DateTimeType implements PrimitiveType, State, Command {
```

In fact, all the openhab types implement Command and State, so they can be provided to Busevent.sendCommand. All we need is to create a DateTimeType out of ZonedDateTime

Maybe this (also apply to update)
```ruby
          def command(command)
            command = command.to_java.strip_trailing_zeros if command.is_a? BigDecimal
            logger.trace "Sending Command #{command} to #{id}"
            BusEvent.sendCommand(self, command.is_a?(Java::OrgOpenhabCoreTypes::Command) ? command : command.to_s)
          end
```

And also deal with our type wrappers to return the underlying type item.

**Comment by pacive** [comment]
Yes, but it would still require that the ZonedDateTime gets converted to a DateTimeType somewhere. Would probably be easiest to override `command` and `update` in the DateTimeItem class anyway.

**Comment by jimtng** [comment]
> Yes, but it would still require that the ZonedDateTime gets converted to a DateTimeType somewhere. 

Agreed.

In terms of the main command/update, WDYT of this:

```ruby
          def normalize(command)
            if command.is_a? BigDecimal
              command.to_java.strip_trailing_zeros 
            elsif command.class.name.start_with? 'OpenHAB::DSL::Types'
              command.openhab_type # to be implemented?
            elsif command.is_a?(Java::OrgOpenhabCoreTypes::Command)
              command
            else
              command.to_s
            end
          end

          def command(command)
            logger.trace "Sending Command #{command} to #{id}"
            BusEvent.sendCommand(self, normalize(command))
          end

          alias << command

          def update(update)
            logger.trace "Sending Update #{update} to #{id}"
            BusEvent.postUpdate(self, normalize(update))
          end
```

**Comment by pacive** [comment]
That could work, but doesn't solve the problem with ZonedDateTime, since it would still hit the command.to_s line?

**Comment by pacive** [comment]
Sorry if I appear too negative, I do agree with you on the point that it would be better to send Command objects instead of strings, since it would reduce the computations when OH needs to reconstruct them as Commands. But we need to think through how to handle this in the best way without loosing support for all the different types of objects we already have.

**Comment by boc-tothefuture** [comment]
Is this something specific to the JRuby library?

**Comment by pacive** [comment]
No, just tested in a jython rule, and it doesn't work there either. The error message is much worse there as well:
```python
from core.rules import rule
from core.triggers import when
from java.time import ZonedDateTime

@rule("Test")
@when("Item Test received command")
def test(event):
    now = ZonedDateTime.now().toString()
    test.log.warn(now)
    events.postUpdate("TestDate", now)
```
```
2021-03-05 14:41:44.757 [WARN ] [jsr223.jython                       ] - Traceback (most recent call last):
  File "/etc/openhab/automation/lib/python/core/log.py", line 65, in wrapper
    return function(*args, **kwargs)
  File "/etc/openhab/automation/lib/python/core/rules.py", line 109, in execute
    self.callback(inputs.get('event'))
  File "<script>", line 10, in test
IllegalArgumentException: java.lang.IllegalArgumentException: The argument 'state' must not be null.
2021-03-05 14:41:44.784 [ERROR] [e.automation.internal.RuleEngineImpl] - Failed to execute rule '34238d9f-9814-4eee-be6d-05dbf7e1a1b8': Fail to execute action: 1
```

**Comment by boc-tothefuture** [comment]
I have no problem with sending the objects instead of strings.  I agree we should also have a uniform (but probably not user documented way because it will mess with things outside the framework) to access the underylying oh_type. 
Should be done by "def_item_delegator" method.

**Comment by ccutrer** [comment]
I didn't read the whole backlog here, but #286, which does directly send commands and updates if they're already an org.openhab.core.types.Type. a ZonedDateTime is not a Type, so it would get stringified before sending, but it would be trivial to detect a ZoneDateTime and wrap it in the proper DateTimeType so that it can be forwarded appropriately. I even added a method so that different item types can do it appropriately (my ColorItem commit does exactly that, to parse strings through HSBType first).
