### ISSUE TITLE
Quantity comparison error with UNDEF items

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#223]
```
Number:Power          NumberPower1
Number:Power          NumberPower2
```

When either/both of these items are UNDEF:

```ruby
require 'openhab'

rule 'x' do
  on_start
  run { logger.error('MORE') if NumberPower1 > NumberPower2 }
end
```
Will trigger this error:

```
09:46:36.266 [ERROR] [y.OpenHAB::DSL::Rules::AutomationRule] - Unexpected type NilClass provided to Quantity initializer (ArgumentError)
In rule: x
<script>:5:in `block in <main>'
<script>:3:in `<main>'
```

On a separate note, @pacive should/could we include the stacktrace inside the library?

Should we require users to check for Item.state? in addition to the comparison, i.e.:
```ruby
if NumberPower1.state? && NumberPower2.state? && NumberPower1 > NumberPower2
```
Or do we treat NumberItem UNDEF as zero in comparisons?

**Comment by pacive** [comment]
> On a separate note, @pacive should/could we include the stacktrace inside the library?

If you set `jsr223.jruby` to debug level in the karaf console you should get the whole stack trace.

**Comment by pacive** [comment]
> Should we require users to check for Item.state? in addition to the comparison, i.e.:
> 
> ```ruby
> if NumberPower1.state? && NumberPower2.state? && NumberPower1 > NumberPower2
> ```
> 
> Or do we treat NumberItem UNDEF as zero in comparisons?

This also relates to #169, where comparisons fail if the state is NULL/UNDEF (and I guess it's the same for all items that implements `<=>`)

**Comment by jimtng** [comment]
This doesn't generate an error though:

```
Number                Number1
Number                Number2
```

```
rule 'x' do
  on_start
  run do
    logger.error('MORE') if Number1 > Number2
    logger.error('LESS') if Number1 < Number2
    logger.error('Equal') if Number1 == Number2
  end
end
```

It will log `Equal`

**Comment by ccutrer** [comment]
I'm it sure if you're saying "It will log equal" [which contradicts what I just said], or if you're saying "[in case that wasn't clear] it will log equal".

So to clarify for myself and others - the current state of main

**Comment by jimtng** [comment]
> After #286, == and != should never throw an exception regardless of what type/state is where. == is well defined on all items to return true IFF the states compare equal, and never raise even in the face of nil on either side. This includes NULL != UNDEF.

> For other comparison operators based off of <=> (<, <=, =>, >) a comparison of incompatible types will raise an error.

I agree. Looking forward to #286
