### ISSUE TITLE
Should switch 'off?' return true for null/undef?

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#23]

**Comment by jimtng** [comment]
I would say that SwitchItem.off? should not return true for null/undef. It should only return true if the state is indeed OFF

There's still an issue about making toggling works i.e. `SwitchItem << !SwitchItem` when SwitchItem is null/undef. So I guess `SwitchItem` should return true only if it's on, and false when it's not on (off/null/undef)

**Comment by boc-tothefuture** [comment]
@jimtng - Could you weigh in on the [forum post](https://community.openhab.org/t/jruby-openhab-rules-system/110598/64?u=broconne)

**Comment by boc-tothefuture** [comment]
Agreed not to do this on the forum.
