### ISSUE TITLE
Event attributes (event.state, event.command) should be wrapped

### ISSUE THREAD

**Issue by pacive** [boc-tothefuture/openhab-jruby#231]
When using e.g. `event.state` or `event.command` in a rule, these contain the OH Types, which makes them harder to use, primarily in comparisons.

Examples:

This rule fails if `event.state` is a QuantityType: (could not coerce Integer to class org.openhab.core.library.types.QuantityType (TypeError))

```ruby
rule 'Low battery notification' do
  changed Batteries.members
  run { |event| logger.warn("Low battery in #{event.item.id}") if event.state < 5 }
end
```

This doesn't work either: (comparison of Time with Java::OrgOpenhabCoreLibraryTypes::DateTimeType failed (ArgumentError))

```ruby
rule 'Schedule vacation mode start' do
  received_command VacationMode_StartDate
  run do |event| 
    VacationMode << ON if Time.now > event.command
   ...
end
```

**Comment by boc-tothefuture** [comment]
What is the to do here?  Convert to JRuby types before dispatching the events?

**Comment by pacive** [comment]
Yes, that would be required, so that the comparisons would be as simple as comparing two items. Not sure where the conversion should be placed though, or how to handle all the different types of events in a good way.

**Comment by boc-tothefuture** [comment]
I like converting to nil if NULL or UNDEF for safe-navigation.  We had lengthy discussions for various types about monkey patch vs delegation.  We ended up delegating the types otherwise we ran into issues of things not working in ranges, etc because they did not extend Number.  We just want to be consistent with when we monkey patch/extend/delegate.

**Comment by jimtng** [comment]
> When using e.g. `event.state` or `event.command` in a rule, these contain the OH Types, which makes them harder to use, primarily in comparisons.
> 
> Examples:
> 
> This rule fails if `event.state` is a QuantityType: (could not coerce Integer to class org.openhab.core.library.types.QuantityType (TypeError))
> 
> ```ruby
> rule 'Low battery notification' do
>   changed Batteries.members
>   run { |event| logger.warn("Low battery in #{event.item.id}") if event.state < 5 }
> end
> ```
> 
> This doesn't work either: (comparison of Time with Java::OrgOpenhabCoreLibraryTypes::DateTimeType failed (ArgumentError))
> 
> ```ruby
> rule 'Schedule vacation mode start' do
>   received_command VacationMode_StartDate
>   run do |event| 
>     VacationMode << ON if Time.now > event.command
>    ...
> end
> ```

I've tested both these scenarios on 4.0.1 and they work now. Are you happy to close this issue @pacive ?

**Comment by pacive** [comment]
Yes, this can be closed
