### ISSUE TITLE
Hash from metadata bug

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#233]
I've spent several days and many long hours trying to figure this out, but I'm still stuck. I hope one of you could help me out on this.

I cannot demonstrate this bug using cucumber because it wipes and recreates the items on each run, so I'll have to describe how to reproduce this bug manually:

Step 1:
Create a dummy item
```
Switch SwitchItem1
```

Step 2:
Create this test.rb file in <CONF>/automation/jsr332/ruby/personal (the usual directory)
```ruby
require 'openhab'

SwitchItem1.meta['test'] = { '1' => { 'moo' => 'cow' } }
logger.error("Meta: for test/1 #{SwitchItem1.meta.dig('test', '1')}")
logger.error("Meta: for test/1/moo '#{SwitchItem1.meta.dig('test', '1', 'moo')}'")
```

You should see the error log in openhab console like this:
```
03:00:07.971 [ERROR] [jsr223.jruby.Object                  ] - Meta: for test/1 {"moo"=>"cow"}
03:00:07.972 [ERROR] [jsr223.jruby.Object                  ] - Meta: for test/1/moo 'cow'
```

So far so good.

Note that at this point, SwitchItem1 has stored the metadata, so in theory, the data is still there even if openhab gets restarted.

Step 3:
Now comment out the line that assigns the metadata in test.rb above, and save it. The file should look like this:
```ruby
require 'openhab'

#SwitchItem1.meta['test'] = { '1' => { 'moo' => 'cow' } }
logger.error("Meta: for test/1 #{SwitchItem1.meta.dig('test', '1')}")
logger.error("Meta: for test/1/moo '#{SwitchItem1.meta.dig('test', '1', 'moo')}'")
```

This is where I'm stuck
```
03:03:11.884 [ERROR] [jsr223.jruby.Object                  ] - Meta: for test/1 {"moo"=>"cow"}
03:03:11.885 [ERROR] [jsr223.jruby.Object                  ] - Meta: for test/1/moo ''
```

Note the second log line (for `SwitchItem1.meta.dig('test', '1', 'moo')`) is blank '' even though `SwitchItem1.meta.dig('test', '1')` shows that it returns a hash `{"moo"=>"cow"}`

I have tried investigating this, although not down to the level of jruby's internals, but still can't figure it out.

It seems that the String used for the key is weird after it's read back from the metadata (java?) but I cannot explain why.

The only way I can get it to work is by doing this:
```ruby
require 'openhab'

var1 = SwitchItem1.meta.dig('test', '1')
logger.error("Meta: for test/1 #{var1}")
logger.error("Meta: for test/1/moo '#{var1.dig('moo')}'")

var1 = var1.map { |k, v| ["#{k} ".strip, v] }.to_h
logger.error("Meta: for test/1/moo '#{var1.dig('moo')}'")
```

Output:
```
03:09:42.339 [ERROR] [jsr223.jruby.Object                  ] - Meta: for test/1 {"moo"=>"cow"}
03:09:42.339 [ERROR] [jsr223.jruby.Object                  ] - Meta: for test/1/moo ''
03:09:42.340 [ERROR] [jsr223.jruby.Object                  ] - Meta: for test/1/moo 'cow'
```

It seems that I need to create a brand new string for the key. Simply calling k.to_s won't do the trick:
```ruby
var1 = SwitchItem1.meta.dig('test', '1')
logger.error("Meta: for test/1 #{var1}")
logger.error("Meta: for test/1/moo '#{var1.dig('moo')}'")

var1 = var1.map { |k, v| [k.to_s, v] }.to_h
logger.error("Meta: after to_s for test/1/moo '#{var1.dig('moo')}'")

var1 = var1.map { |k, v| ["#{k} ".strip, v] }.to_h
logger.error("Meta: after strip for test/1/moo '#{var1.dig('moo')}'")
```

output:
```
03:17:57.384 [ERROR] [jsr223.jruby.Object                  ] - Meta: for test/1 {"moo"=>"cow"}
03:17:57.384 [ERROR] [jsr223.jruby.Object                  ] - Meta: for test/1/moo ''
03:17:57.385 [ERROR] [jsr223.jruby.Object                  ] - Meta: after to_s for test/1/moo ''
03:17:57.385 [ERROR] [jsr223.jruby.Object                  ] - Meta: after strip for test/1/moo 'cow'
```
EDIT: indeed, rubocop suggested using transform_keys instead of map.to_h, since only the keys need to be changed, but that's beside the point, I guess. Either way would work

**Comment by jimtng** [comment]
To show you how weird this is:

```ruby
require 'openhab'

var1 = SwitchItem1.meta.dig('test', '1')
var1 = var1.merge({ 'moo' => 'another cow' }) # this should overwrite the 'moo' key but it doesn't
logger.error("Meta: for test/1 #{var1}")

var1.each { |k, v| logger.error("#{k} is a #{k.class} #{k.bytes} value: #{v}") }
```

output, notice the duplicate keys, and also notice the NPE
```
04:01:28.652 [ERROR] [jsr223.jruby.Object                  ] - Meta: for test/1 {"moo"=>"cow", "moo"=>"another cow"}
04:01:28.652 [ERROR] [jsr223.jruby.Object                  ] - moo is a String [109, 111, 111] value: cow
04:01:28.652 [ERROR] [jsr223.jruby.Object                  ] - moo is a String [109, 111, 111] value: another cow
04:01:28.653 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/ruby/personal/test.rb': org.jruby.embed.EvalFailedException: java.lang.NullPointerException
```

**Comment by pacive** [comment]
Hashes uses the hash values of the objects used as keys and maps that to the value (or it's memory address, not certain on the details). My hypothesis is that the key returned from the oh medadata registry somehow hashes to a different value than a string created in ruby, which makes them effectively different keys. 

This might be a bug in jruby, but can also be due to how we treat the metadata in the library.

**Comment by boc-tothefuture** [comment]
You are hitting an issue related to #46.   Something I hit when playing with different memory models.

The String object being placed into the hash from one thread is in a different ruby context than any other thread.  Therefore when the hash checks if they are the same object it returns false. 

We could look at maybe doing a string.intern to see what happens there? We are going to have to play around with it.

**Comment by jimtng** [comment]
11 minutes later, it still works:

```
11:11:52.604 [ERROR] [jsr223.jruby.Object                  ] - Meta: commanded cow
```

**Comment by jimtng** [comment]
I don't know if this is related, but SwitchItem1.meta['test'] returns our MetadataItem class, which is a SimpleDelegator for metadata.configuration, which is a `Java::JavaUtil::Collections::UnmodifiableMap`

However, SwitchItem1.meta['test']['1'] is a Hash.

```ruby
logger.info("SwitchItem1.meta['test'] is a #{SwitchItem1.meta['test'].class}") 
logger.info("SwitchItem1.meta['test'].__getobj__ is a #{SwitchItem1.meta['test'].__getobj__.class}") 
logger.info("SwitchItem1.meta['test']['1'] is a #{SwitchItem1.meta['test']['1'].class}") 
```

output:
```
13:19:14.797 [ERROR] [jsr223.jruby.Object                  ] - SwitchItem1.meta['test'] is a OpenHAB::DSL::MonkeyPatch::Items::Metadata::MetadataItem
13:19:14.797 [ERROR] [jsr223.jruby.Object                  ] - SwitchItem1.meta['test'].__getobj__ is a Java::JavaUtil::Collections::UnmodifiableMap
13:19:14.798 [ERROR] [jsr223.jruby.Object                  ] - SwitchItem1.meta['test']['1'] is a Hash
```

It remains that SwitchItem1.meta['test']['1'] is a Hash. However, obviously it's created by the java code (as an element of Java::JavaUtil::Collections::UnmodifiableMap), I don't know what is the java equivalent of ruby's hash and how jruby would convert it to a ruby Hash.

**Comment by jimtng** [comment]
This caused NPE:
```ruby
require 'openhab'
require 'json'

var1 = SwitchItem1.meta.dig('test', '1')
var1.to_json
```

**Comment by pacive** [comment]
> I don't know if this is related, but SwitchItem1.meta['test'] returns our MetadataItem class, which is a SimpleDelegator for metadata.configuration, which is a `Java::JavaUtil::Collections::UnmodifiableMap`
> 
> However, SwitchItem1.meta['test']['1'] is a Hash.
> 
> ```ruby
> logger.info("SwitchItem1.meta['test'] is a #{SwitchItem1.meta['test'].class}") 
> logger.info("SwitchItem1.meta['test'].__getobj__ is a #{SwitchItem1.meta['test'].__getobj__.class}") 
> logger.info("SwitchItem1.meta['test']['1'] is a #{SwitchItem1.meta['test']['1'].class}") 
> ```
> 
> output:
> 
> ```
> 13:19:14.797 [ERROR] [jsr223.jruby.Object                  ] - SwitchItem1.meta['test'] is a OpenHAB::DSL::MonkeyPatch::Items::Metadata::MetadataItem
> 13:19:14.797 [ERROR] [jsr223.jruby.Object                  ] - SwitchItem1.meta['test'].__getobj__ is a Java::JavaUtil::Collections::UnmodifiableMap
> 13:19:14.798 [ERROR] [jsr223.jruby.Object                  ] - SwitchItem1.meta['test']['1'] is a Hash
> ```
> 
> It remains that SwitchItem1.meta['test']['1'] is a Hash. However, obviously it's created by the java code (as an element of Java::JavaUtil::Collections::UnmodifiableMap), I don't know what is the java equivalent of ruby's hash and how jruby would convert it to a ruby Hash.

The oh metadata class stores the configuration as a `Map<String, Object>`, so if you store a nested (ruby) Hash, this would be perfectly valid. I wonder what would happen if this should be read from somewhere else. Can you check via the rest api how it looks?

**Comment by jimtng** [comment]
> I wonder what would happen if this should be read from somewhere else.

Could you clarify what you mean please?

---

I made a recursive rehash method to "clean up" the data. This makes to_json happy (no longer throwing an NPE)

```ruby
def rehash(hash)
  return hash unless hash.is_a? Hash

  hash.transform_keys { |k| ''.concat k }
      .transform_values do |v|
    case v
    when Hash then rehash(v)
    when String then ''.concat(v)
    else v
    end
  end
end
```

**Comment by pacive** [comment]
> Could you clarify what you mean please?

I mean if the metadata you add in the script can be accessed from somewhere else in the system, outside of the ruby rules. What is output from the `/items/{item name}/` endpoint in the rest api e.g?

**Comment by jimtng** [comment]
> I mean if the metadata you add in the script can be accessed from somewhere else in the system, outside of the ruby rules. What is output from the `/items/{item name}/` endpoint in the rest api e.g?

REST just returns the metadata as json

**Comment by pacive** [comment]
> > I mean if the metadata you add in the script can be accessed from somewhere else in the system, outside of the ruby rules. What is output from the `/items/{item name}/` endpoint in the rest api e.g?
> 
> REST just returns the metadata as json

And the configuration that you added is printed correctly? What about the `{USERDATA}/jsondb/org.openhab.core.items.Metadata.json` file? Is everything present there?

Sorry for all the questions, just trying to figure out how this works! 🙂

**Comment by jimtng** [comment]
> And the configuration that you added is printed correctly? 

Yes

> What about the `{USERDATA}/jsondb/org.openhab.core.items.Metadata.json` file? Is everything present there?

Yes

They all just look like harmless plain json text

**Comment by pacive** [comment]
Then everything should survive a restart, but when OH reads the values from the jsondb to reconstruct the metadata it would no longer be a Hash. Could that be why you get an NPE with the dig method? Or perhaps jruby converts all java maps to hashes?

BTW, the Hash class already have a `rehash` method, does that work instead of using the one you created?

**Comment by jimtng** [comment]
> Then everything should survive a restart, but when OH reads the values from the jsondb to reconstruct the metadata it would no longer be a Hash. Could that be why you get an NPE with the dig method? Or perhaps jruby converts all java maps to hashes?

It just seems that the "String" object within the hash (both as the key and as the value) are strange, possibly thread related issue.



> BTW, the Hash class already have a `rehash` method, does that work instead of using the one you created?

Yes I noticed this in the Hash documentation and tried it. It didn't solve the issue.

**Comment by boc-tothefuture** [comment]
It is less of a "threading" issue and more of a "context" issue.  When OpenHAB parses a file it asks JSR223 for a context to process it in.  In the current setup, each file is it's own context.  In this case think of the context almost as if it were its own JVM (it isn't, but think of it that way).

What is happening is when accessed by different files there are multiple contexts accessing the same hash.  I will have to go back and see if I can find out what the JRuby people had me run to figure it out. But essentially the String class in one context is not the same as the String class in the other context.  

So everything hashes correctly, but when the equals happens and an instanceof check is applied it comes back false.

I haven't played with it, but we may be able to fix this by doing a to_java before we insert the metadata and/or on get.  If that doesn't work we could try creating a Java::Lang::String before we insert and again before we check.

**Comment by boc-tothefuture** [comment]
@jimtng - Have you tried converting to string?  Do you have a branch with a failing test case we can look at?

**Comment by jimtng** [comment]
> @jimtng - Have you tried converting to string? Do you have a branch with a failing test case we can look at?

Converting the keys and values to string using ''.concat(key) and ''.concat(value) solved the problem.


I finally came up with a cucumber test that can demonstrate this problem:
```
Feature:  metadata
  Items support accessing metadata

  Background:
    Given Clean OpenHAB with latest Ruby Libraries
    And items:
      | type   | name       |
      | Switch | TestSwitch |
    And a deployed rule:
      """
      TestSwitch.meta['animalsounds'] = { 'land' => { 'cow' => 'moo'}}
      logger.info("Metadata animalsounds created for TestSwitch: #{TestSwitch.meta['animalsounds']}")
      """

  Scenario Outline: Metadata key works when assigned in the same rule
    Given code in a rules file:
      """
      TestSwitch.meta['animalsounds'] = {"land"=>{"cow"=>"moo"}}
      code = '<metadata>'
      logger.info("#{code}: #{<metadata>}")
      """
    When I deploy the rules file
    Then It should log '<metadata>: <value>' within 5 seconds
    Examples:
      | metadata                                           | value                    |
      | TestSwitch.meta["animalsounds"]                    | {"land"=>{"cow"=>"moo"}} |
      | TestSwitch.meta.dig("animalsounds", "land")        | {"cow"=>"moo"}           |
      | TestSwitch.meta.dig("animalsounds", "land", "cow") | moo                      |


  Scenario Outline: Metadata key works when not assigned in the same rule
    Given code in a rules file:
      """
      code = '<metadata>'
      logger.info("#{code}: #{<metadata>}")
      """
    When I deploy the rules file
    Then It should log '<metadata>: <value>' within 5 seconds
    Examples:
      | metadata                                           | value                    |
      | TestSwitch.meta["animalsounds"]                    | {"land"=>{"cow"=>"moo"}} |
      | TestSwitch.meta.dig("animalsounds", "land")        | {"cow"=>"moo"}           |
      | TestSwitch.meta.dig("animalsounds", "land", "cow") | moo                      |

  Scenario Outline: Comparing against a hash literal when metadata assigned in the same rule
    Given code in a rules file:
      """
      TestSwitch.meta['animalsounds'] = {"land"=>{"cow"=>"moo"}}
      logger.info("Metadata checks out") if <metadata> == <value>
      """
    When I deploy the rules file
    Then It should log 'Metadata checks out' within 5 seconds
    Examples:
      | metadata                                           | value                    |
      | TestSwitch.meta["animalsounds"]                    | {"land"=>{"cow"=>"moo"}} |
      | TestSwitch.meta.dig("animalsounds", "land")        | {"cow"=>"moo"}           |
      | TestSwitch.meta.dig("animalsounds", "land", "cow") | "moo"                    |

  Scenario Outline: Comparing against a hash literal when metadata NOT assigned in the same rule
    Given code in a rules file:
      """
      logger.info("Metadata checks out") if <metadata> == <value>
      """
    When I deploy the rules file
    Then It should log 'Metadata checks out' within 5 seconds
    Examples:
      | metadata                                           | value                    |
      | TestSwitch.meta["animalsounds"]                    | {"land"=>{"cow"=>"moo"}} |
      | TestSwitch.meta.dig("animalsounds", "land")        | {"cow"=>"moo"}           |
      | TestSwitch.meta.dig("animalsounds", "land", "cow") | "moo"                    |
```

**Comment by jimtng** [comment]
@boc-tothefuture I could write a "patch" PR that would perform a recursive string conversion on the return of the metadata value. However, it feels wrong to have to do this.

**Comment by jimtng** [comment]
@boc-tothefuture is this relevant? https://javadoc.io/static/org.jruby/jruby-core/9.2.9.0/org/jruby/RubyInstanceConfig.html#CONSISTENT_HASHING_ENABLED

**Comment by boc-tothefuture** [comment]
I don't think it will because it is not a hashing issue but a class equality issue. 

Do you have an open branch you push as a WIP?

**Comment by jimtng** [comment]
> I don't think it will because it is not a hashing issue but a class equality issue.

I'm not so sure about that. eql? relies on hash. My test shows that the hash values are indeed different.



> Do you have an open branch you push as a WIP?

No, because at this point I have no idea how to fix it, so there's nothing to push :(

**Comment by boc-tothefuture** [comment]
Just pushing with your test case would be a place for us to start.
