### ISSUE TITLE
mimemagic dependency

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#236]
I tried testing with Openhab 3.1.0M2 by modifying rakelib/openhab.rake.

It set up and installed openhab 3.1.0M2 correctly, however when running a cucumber test I got this:

```
Ignoring mimemagic-0.4.3 because its extensions are not built. Try: gem pristine mimemagic --version 0.4.3
Gem::MissingSpecError: Could not find 'nokogiri' (~> 1) among 26 total gem(s)
```

It seems the newer versions of mimemagic need nokogiri 
https://rubygems.org/gems/mimemagic/versions/

nokogiri is a binary gem?

**Comment by jimtng** [comment]
You could try this by just running 

```
bundle exec rake openhab:clobber 
bundle exec rake openhab:setup
bundle exec cucumber features/anything
```

**Comment by jimtng** [comment]
See https://github.com/rails/rails/issues/41750
mimemagic 0.3.6 and older have been yanked. The only available version now depends on nokogiri which seems to require compiling

**Comment by boc-tothefuture** [comment]
Ughh.. I don't think we want to require nokogiri..  That is a large burden.

**Comment by pacive** [comment]
Is it possible to remove the dependency (and make the ImageItem temporarily less functional) until we can solve this properly? It seems this missing dependency currently prevents the helper library from being installed on new systems.

**Comment by boc-tothefuture** [comment]
Yes, I think we should remove it.. They updated the library, but it now requires a file to be installed on the host machine: https://github.com/mimemagicrb/mimemagic

I don't think that will work for us.
