### ISSUE TITLE
store_states failed on decorated items

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#241]
OpenHAB::DSL::States::store_states calls BusEvent.storeStates which expects OrgOpenhabCoreItemsItem object. This means passing our decorated items won't work.

It appears that we haven't got around to standardising on jruby item::oh_item to make things like store_states able to access the underlying openhab object.

What's the best way of solving this?

**Comment by boc-tothefuture** [comment]
Best bet is to probably push forward and make that conversion.  I would need to go back and see how many items we would need to change.
