### ISSUE TITLE
Heads up: Changed UoM libraries in OH

### ISSUE THREAD

**Issue by pacive** [boc-tothefuture/openhab-jruby#245]
OH has recently changed the UoM libraries (https://github.com/openhab/openhab-core/commit/91307993ad2fbe1b357f1dab8d694d679e67ca8c) which are also used in our NumberItem/Quantity classes. I would assume this breaks the helper library in recent snapshots and will soon in milestones when M5 is released. However, updating to use the new UoM libraries would instead break it if running 3.0. 

How would we best handle this? We should assume some users would still be on 3.0 even after 3.1 is released, so we would need to support both versions. Is it possible to rework so we won't have to import the libraries directly?

**Comment by boc-tothefuture** [comment]
We will have to think about how we handle OH version differences.  Not sure how we would rework it to not import directly.  The way the python libraries handle it is they try to import the most recent libraries and if that fails they fall back to the older libraries.

**Comment by pacive** [comment]
Going the python library way, it should be possible using something like:
```ruby
begin
  java_import 'tech.units.indriya.format.SimpleUnitFormat'
  java_import 'tech.units.indriya.AbstractUnit'
rescue NameError => e
  java_import 'tec.uom.se.format.SimpleUnitFormat'
  java_import 'tec.uom.se.AbstractUnit'
end
```
+ check if there are any other differences in the 2.1.2 version of the javax.measure interfaces that needs to be handled similarly.

Not sure how we could write tests for it though, that would require to install an additional OH instance in the testing environment. Would manual testing be enough in this case?

**Comment by boc-tothefuture** [comment]
The test setup in github is a "matrixed" setup.  We only have one version, but it is trivial to add another.  I think locally we just test against latest and we can test against n-1 in the pipeline.

**Comment by pacive** [comment]
I have examined it a bit, and managed to make the imports work, as well as where some method names differ. But the new library seems to work somewhat differently, which makes a lot of tests in quantity.feature and units_of_measurement.feature fail. I don't know the ins and outs of the Quantity class well enough to know where it breaks or how to adapt it (especially in a way that doesn't break backwards-compatibility). There are also some other changes to OH core that causes slightly different behaviour (e.g. printing Number Item values as 25 instead of 25.0) which doesn't affect functionality, but breaks some tests. Will make a WIP PR for further discussions.
