### ISSUE TITLE
event.item returns the item state, not the item name

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#26]
In the README.md examples, e.g.

```
rule 'Access Event Properties' do
  changed TestSwitch
  run { |event| logger.info("#{event.item} triggered from #{event.last} to #{event.state}") }
end
```

It was assumed that "#{event.item}" would return the item's name, but since Item evaluates to its state, the logging that occurred looks like:
```
11:09:16.958 [INFO ] [.OpenHAB::Core::DSL::Rule::RuleConfig] - OFF triggered from ON to OFF
```

If this is the intended behaviour, we need to change the examples in the readme to say "#{event.item.name}"

**Comment by boc-tothefuture** [comment]
Good catch.  The original behavior would return the label/name.  The docs are wrong.
