### ISSUE TITLE
openhab specific rubocop rules

### ISSUE THREAD

**Issue by ccutrer** [boc-tothefuture/openhab-jruby#262]
thoughts?

things I've already thought I should prefer:

Prefer calling helper command method instead of shoveling a command object:
`SwitchItem.on` instead of `SwitchItem << ON`

Prefer comparing directly against an item instead of calling state: (I'm still exploring this one, with how NULL and UNDEF work with comparisons, since I see tickets about them)
`NumberItem < 100` instead of `NumberItem.state < 100`

Prefer `each` on GroupItem instead of `all_members.each`:
`GroupItem.each { ... }` instead of `GroupItem.all_members.each { ... }`

Prefer helper state method instead of comparison to state object:
`ContactItem.open?` instead of `ContactItem.state == OPEN` or `ContactItem == OPEN`

**Comment by ccutrer** [comment]
do you have a preference for how this is packaged? (same gem? different gem, same repo? different repo entirely?)

**Comment by boc-tothefuture** [comment]
I would think different repo/gem because the current gem is going to be tied to JRuby running inside of OpenHAB.  Right?

**Comment by ccutrer** [comment]
👍 that's fine with me. do you have a preference for it being under your user on GitHub?

**Comment by boc-tothefuture** [comment]
Nope - I think it can be under yours.

**Comment by ccutrer** [comment]
https://github.com/ccutrer/rubocop-openhab-scripting
