### ISSUE TITLE
.seconds only support on integer, not float

### ISSUE THREAD

**Issue by ccutrer** [boc-tothefuture/openhab-jruby#263]
I want a timer to run in less than 1 second:

`after 0.1.seconds {}`, but I get an error that seconds isn't defined on the float

**Comment by boc-tothefuture** [comment]
Currently if you want to do that you would do 100.ms or 100.millis or 100.milliseconds 

Right now we are just using the methods in java.time.Duration, we would have to think about how we would handle that with floats if we wanted the proposed alternative.
