### ISSUE TITLE
SwitchItem.toggle

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#27]
Is there a reason why having SwitchItem.toggle is a bad idea?

I can do a PR, essentially adding this, unless there's a better way
```
  def toggle
    command(on? ? OnOffType::OFF : OnOffType::ON)
  end
```

**Comment by boc-tothefuture** [comment]
How does that differ from the current use of !SwitchItem ? 

I am ok with adding it if you think there is utility.

**Comment by jimtng** [comment]
One could do `GroupItem.each(&:toggle)`

**Comment by boc-tothefuture** [comment]
👍
