### ISSUE TITLE
Get a collection of all Items, including Groups

### ISSUE THREAD

**Issue by pacive** [boc-tothefuture/openhab-jruby#288]
I have a rule for controlling scenes that iterates through all Items and set their state according to a value defined in the items metadata. For my use case I want to be able to define this on groups as well (instead of setting the same value to all the group's members). Since the `items` collection filters out the GroupItems I had to concatenate this with the `groups` collection, but this no longer works after #278. The method I used was this:
```ruby
def apply_scene(scene)
  (items + groups).each do |item|
    config = item.meta['scene']
    next unless config && %w[on active true].include?(config.value.downcase)

    command = config[scene.to_s]
    next unless command

    command == 'custom' ? send("#{item.name.downcase}_#{scene}") : item << command
  end
end
```
My main question is: is there a reason for filtering out the groups? In OH lingo they're Items just like anything else (and the other rule languages include them in the `items`-array/list). Or is there a different way of iteration through all Items in a similar way?

**Comment by boc-tothefuture** [comment]
Ok, so the concatenation doesn't work.

I had explicitly filtered out groups from items because in my use cases I almost always operate on them as distinct entities.  If I am the only one that does that we could undo that.  While groups are "items" in the end, when I am iterating over them I treat them separately.   If it is just me, I can always do the filtering on my side.

**Comment by ccutrer** [comment]
I should fix concatenation, but I agree with @pacive - `items` should include all items. I'd probably create a buggy rule that tried to look up a group through `items`. I only noticed yesterday that there is a separate `groups` method, and I missed it in the "lazy load" commit.

**Comment by pacive** [comment]
The GroupItem class in OH core has an overloaded `members`-method that take a Predicate filter argument. I think Jruby can translate a block to this, so it could be used.
