### ISSUE TITLE
sort out DSL method availability

### ISSUE THREAD

**Issue by ccutrer** [boc-tothefuture/openhab-jruby#294]
DSL methods have been added to the object model in several ways inconsistently, and their visibility needs to be sorted out.
 (constants too, but I want to address methods for now with this issue).

There should be three levels:
 * Modules `extend`ed onto `main` (the top-level object). These methods are _only_ available from the top level, or other top level methods/blocks. This should include things like `rule`.
 * Modules `include`d onto `Object` (implicitly what happens when you `include` onto `main`): These methods are available on _any_ object, anywhere, called in any way. I'm not sure what, if anything, truly belongs here. Candidates are entity lookup (`method_missing` and `const_missing` support that allows you to reference items and things as first-class named objects). These are kind of dangerous because any library a person might use will see these methods. And while anything they define will override stuff we add here, it still introduces possibilities for mis-understandings. Case in point - `OpenHAB::DSL::Items` is `include`d onto object, so the `items` method is available on _any_ object, and even tripped our tests because we have something calling `SomeGroupItem.items` which was returning _all items in OpenHAB_ rather than the expected items belonging just to that group item.
 * Modules `include`d onto `Object`, but with instance methods marked as `module_function`. `module_function` both marks the instance method as private, and copies it to the module's singleton. The end result is that the methods are callable explicitly (like `OpenHAB::DSL::Items.items`) _or_ as a "bare" method call (`items`), but never as an instance method on an object (`SomeGroupItem.items` -- even though technically the method exists, it's not callable because it's private -- this is how all the methods in `Kernel` are defined, like `puts`). Clearly I believe `items` belongs in this category :).

As an aside, even if something is in the first category, it can still be included into other contexts like `RuleConfig` for use in the block for setting up a rule. Right now this is exactly how `OpenHAB::Core::EntityLookup` works - it's `extend`ed onto `main`, and `include`d into `RuleConfig`.

`rule` is clearly in the first category.

I really can't think of anything that should be in the second category. But there are several things that I'm not sure if they should be in the first category or the third. Should `items` be available _anywhere_, or only at top-level, or within rule config and rule execution blocks? Basically, should this work in my own class?:

```ruby
class Something
  def my_method
    items["MySwitch"]
  end
end

rule "when something happens" do
  changed MySwitch
  run do
    Something.new.my_method
  end
end
```

Seems like most other methods fit in this category - actions, `items`, `things`, `groups`, `unit`.

**Comment by boc-tothefuture** [comment]
I am sure there is a lot of inconsistency with how things are added onto the base objects and it should be cleaned up. It would be nice if we could have rules script files run in some other object besides the base object.  However, it doesn't appear ruby/jruby supports that, although it would be helpful if all the script files by default could run inside of an OpenHAB ruby object I looked at that, but couldn't find a way to do it without creating additional overhead of having to wrap everything inside of an object that the user would have to construct like
```
openab do
....
end
``` 
which I wanted to avoid.

The reason everything like items, groups, etc is available everywhere is to allow the dynamic construction of rules using the ruby language itself - I modeled this off of Chef. 

You can do:
```
items.select { |item| some_matcher }
         .each do |item|
            rule "Rule for item #{item}" do
              changed item
              run do
                 ... whatever you want to do
              end
            end
         end
```

We would need to think carefully about taking this sort of functionality out, because the ability to dynamically create rules is very powerful.

**Comment by ccutrer** [comment]
Note that your example (an items loop with a rule defined inside) still works if `rule` is only defined on `main` - `self` is still `main` at that point. Your point still stands though, that someone may want to dynamically define rules anywhere, including inside of a class they create to wrap up logic on how to gather those rules together. I could see myself doing this for my complicated A/V rules.

So I think I'm currently leaning towards rules, items, groups going with strategy 3 (module_function, available everywhere but not as methods on every object).

I almost asked about actions and units, but I immediately saw that I might set a rule up to call a method on my own class, and then need those things. So same story.

**Comment by boc-tothefuture** [comment]
```
So I think I'm currently leaning towards rules, items, groups going with strategy 3 (module_function, available everywhere but not as methods on every object).
```

What impact would that have?

**Comment by ccutrer** [comment]
Assuming my quick glance at the code was correct, `rule` would now be available for use inside non-top-level methods, and `items` would no longer be available for use on _any_ object (i.e. `5.items` would no longer work).

**Comment by jimtng** [comment]
It seems that #523 and #527 are related to this. I started having a look for classes that have been included into the top level and spotted a few that could / should be hidden from the top level. For example, the `Timer` class, but there are a few others.

Like in #527 should we move them into OpenHAB::Core[::Something] ?
