### ISSUE TITLE
Comparison problems after #286

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#298]
After #286, I noticed a few changes / errors

1. Whenever a rule file is loaded, it no longer logs the current jruby library version
2. This code now caused an error:
```
logger.info("XX") if Number1 == Number2
```
where Number1 = Number2 = NULL

The error message was:
```
08:31:28.068 [ERROR] [y.OpenHAB::DSL::Rules::AutomationRule] - undefined method `>' for true:TrueClass (NoMethodError)
In rule: x
/openhab/conf/automation/jsr223/ruby/personal/test.rb:44:in `block in <main>'
/openhab/conf/automation/jsr223/ruby/personal/test.rb:40:in `<main>'
```

3. `say` caused an error inside a rule when triggered by a changed trigger, but works with `on_start`:
```
rule 'x' do
  on_start
  run do
    say 'on_start' # This works
  end
end

rule 'FR: triggered ' do
  changed gCameraMotions.members, to: ON
  run do |_item|
    say 'changed' # this caused an error
  end
end
```

Error message:
```
08:28:33.990 [ERROR] [y.OpenHAB::DSL::Rules::AutomationRule] - class or module required (TypeError)
In rule: FR: triggered
/openhab/conf/automation/jsr223/ruby/personal/test.rb:55:in `block in <main>'
```

**Comment by ccutrer** [comment]
I've fixed the comparison problems with #299. I'm really confused how on earth I affected the scope of actions, but I'll dig when I get a minute (wife is pulling me away for now).

**Comment by ccutrer** [comment]
ohh, I see on the actions. it uses PercentType internally, I'm sure that a reference broke in there. I'll write a test and fix

**Comment by ccutrer** [comment]
for the logging of version on script load, I'm not sure what to say. we have a test that specifically checks for that. and I'm seeing it in my log. maybe your log level got tweaked? it's at info level
