### ISSUE TITLE
storeStates / restoreStates

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#31]
I sometimes use the above methods. Currently this is doable with:
```
java_import org.openhab.core.model.script.actions.BusEvent

states = BusEvent.storeStates([Item1, Item2, Group1])
BusEvent.restoreStates(states)
```

I'd like to eliminate having to have a java_import on top of my rule script. Could/should we include this inside openhab.rb or somewhere more appropriate?

We can also create a Ruby implementation of these methods, as an alternative.

Is there a more Ruby-ish way of doing this?

**Comment by boc-tothefuture** [comment]
What does this do?  This just push things to the persistence service?

**Comment by jimtng** [comment]
This has nothing to do with persistence service.

All it really does is create a hash containing the Item as the key and the current state of that item.
You can then change the state of that item, then later on, restore the state of that item from the saved hash.

pseudocode:
```
# Item1 was on, Item2 was OFF
savedstate = BusEvent.storeStates(Item1, Item2)
Item1 << OFF
Item2 << ON
delay 1.minute
BusEvent.restoreStates(savedstate)
# Item1 is now ON, and Item2 is now OFF, as per their corresponding states when storeStates was called
```

**Comment by boc-tothefuture** [comment]
That is interesting. Looking at the code it doesn't even use the Bus.. It does do some things with groups, but it is mostly just a hashmap.

Restore states does either a command or an update depending on if the state is a command or not.  So the ruby implementation above isn't 1 for 1. 

I think, in ruby we would want to use a block context for this instead.. Ignore the method names..

```
  Item1.restore_state_when_done do 
     Item1 << OFF
  end

```

**Comment by boc-tothefuture** [comment]
To handle multiple items you would maybe consider

restore_states Item1, Item2 do

end

**Comment by jimtng** [comment]
In one scenario, I save the states in one rule (leaving home) and restore the states in another rule (arriving home). Not sure if that can be done using a block context.

**Comment by boc-tothefuture** [comment]
I would think it would go into openhab/core/dsl/states.rb and then get included via the DSL module.

Usually in ruby if you don't pass it a block it returns an object for you to operate on.

so it would be either
```
restore_state Item1, Item2 do

end
```

or
```
states = restore_states Item1, Item2
other code

states.restore
```

or something like that.

**Comment by jimtng** [comment]
I made the following implementation - briefly tested. I haven't yet tested how it integrates into the OpenHAB::Core::DSL module, if that's even the right place to put it.

A cucumber test needs to be developed for it too. Would this then bump the version up to 2.4.0? I'm not familiar with semver - does it bump up one minor version for every little additional feature?

**Comment by boc-tothefuture** [comment]
If we send the Ruby hash to the BusEvent.restoreStates does JRuby automatically convert that for us to a JavaHash? (JRuby probably uses a Java hashmap under the covers).  That would allow us to use the code in the core and automatically get any changes provided there. 

Haven't tested anything, but I think you can do this:
```
def store_states(*items, &block)
  java_import org.openhab.core.model.script.actions.BusEvent
  BusEvent.storeStates(items).to_h.tap do |states|
     def states.restore 
       BusEvent.restoreStates(self)
     end

     if block_given?
       yield states #Assuming we want to provide the hash to the block? 
       states.restore
    end
  end
end
```

**Comment by jimtng** [comment]
There are several points:

1. I noticed something different/strange with the core's version of restoreStates. It seems able to sendCommand for items that would normally not accept the value. Example: one can storeStates(ContactItem) and restoreStates(), and it would send a command to the ContactItem. When I tried manually sending a command ContactIitem.command(CLOSED), it would issue a warning that ContactItem only accepts RefreshType. This is why I implemented mine using checks against getAcceptedCommandTypes instead. The core implementation checks if the state is a Command (CLOSED is a command).

2. Core's storeStates doesn't accept JRuby's Group (since it's a bit of a hack). This is not a big deal, I can fix that up prior to calling it. 

3. I was thinking about storing the states as strings { "ItemName" => "State" } instead of { ItemObject => ValueObject }. The reason for this is so the stored states can be serialised as string / json / yaml. However, I'm not quite sure on this yet, especially not sure how to differentiate UNDEF and NULL values vs a string that contains the word "UNDEF" and "NULL".

**Comment by boc-tothefuture** [comment]
Interesting on point 1.  I guess the original implementation didn't consider restoring contacts.  Does it make sense to ever restore a contact?  

On point 2.  I didn't think about that.  You could use a map on items and call .group.  We should probably consider a .to_oh on on delegates that returns the underlying oh object so it could be uniformly called on an array of objects.

On point 3, I haven't looked at it, but you could look at overriding to_json on the object.

Looking good so far!

**Comment by jimtng** [comment]
I've decided not to do #3 at this point. I haven't got a need for it, so far. It was just a thought.



> Interesting on point 1. I guess the original implementation didn't consider restoring contacts. Does it make sense to ever restore a contact?

Perhaps not... but since it is possible to change a contact's state, it should also be possible to restore its state, and indeed restoreStates can do it by sending a command.
