### ISSUE TITLE
Logging prefixes are now different

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#313]
I am not sure exactly what changed, guessing it happened in #286  ? 

However, we can no longer set the log level for jruby using 'jsr223.jruby' as the names for some of the classes seemed to have changed.

I see logger names like: 'jsr223.jruby.OpenHAB::DSL::Rules::AutomationRule'

I am pretty sure that used to be 'jsr223.jruby.OpenHAB.DSL.:Rules.AutomationRule'

**Comment by ccutrer** [comment]
inside a rule _is_ still in top-level context. (`self` is still `main`). @boc-tothefuture is working on the ticket to change the logger name for that context though
