### ISSUE TITLE
Rule description

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#32]
It would be nice to be able to set rule description. This can be implemented as a "property" similar to "on_start, changed, run, triggered", etc.

```ruby
rule 'rulename' do
  description 'rule description'
  <triggers>
  <execution blocks>
end
```

**Comment by boc-tothefuture** [comment]
I agree and that is probably the right implementation method.  

What is the description used for?  I always saw it in the Jython stuff (never saw it in DSL) and never understood where it got used?  Does it just show up in the UI?

**Comment by jimtng** [comment]
It is just a way to provide more details about what the rule does, and it does show up in the GUI although I don't usually look in there / use the GUI. 

Anyway I have managed to figure out how to add this, and tested it, so I'll submit a PR very shortly.
