### ISSUE TITLE
Unable to handle OnOffType command mixed with numeric in a case statement for DimmerItem

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#328]
This test currently breaks:

```
  Scenario Outline: Handle Numeric and OnOffType command in a case
    Given code in a rules file
      """
      rule 'commanded' do
        received_command DimmerOne
        run do |event|
          logger.error(event.command.class)
          case event.command
          when 0..50 then logger.info("up to 50%")
          when 51..100 then logger.info("greater than 50%")
          when ON then logger.info("It is ON")
          when OFF then logger.info("It is OFF")
          end
        end
      end
      DimmerOne << <state>
      """
    When I deploy the rules file
    Then It should log "<log>" within 5 seconds
    Examples:
      | state | log              |
      | ON    | It is ON         |
      | OFF   | It is OFF        |
      | "10"  | up to 50%        |
      | "50"  | up to 50%        |
      | "100" | greater than 50% |
```

This is because comparison between OnOffType and Integer (the 0..50 and 51..100) raised an exception inside `type.rb`

```
18:14:10.211 [TRACE] [OrgOpenhabCoreLibraryTypes::OnOffType] - Coercing ON (Java::OrgOpenhabCoreLibraryTypes::OnOffType) as a request from Integer
18:14:10.211 [ERROR] [y.OpenHAB::DSL::Rules::AutomationRule] - can't convert Integer into Java::OrgOpenhabCoreLibraryTypes::OnOffType (TypeError)
In rule: commanded
/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-4.6.0/lib/openhab/dsl/types/type.rb:32:in `coerce'
org/jruby/RubyRange.java:754:in `cover?'
org/jruby/RubyRange.java:706:in `include?'
org/jruby/RubyRange.java:749:in `==='
<script>:11:in `block in <main>'
org/jruby/RubyBasicObject.java:2694:in `instance_exec'
/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-4.6.0/lib/openhab/dsl/rules/automation_rule.rb:332:in `process_run_task'
/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-4.6.0/lib/openhab/dsl/rules/automation_rule.rb:277:in `process_task'
/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-4.6.0/lib/openhab/dsl/rules/automation_rule.rb:262:in `process_queue'
/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-4.6.0/lib/openhab/dsl/rules/automation_rule.rb:58:in `execute'
```

**Comment by boc-tothefuture** [comment]
I believe a dimmer is 'ON' if > 0 and 'OFF' if = 0.

So it tracks for me that the case statements work this way.

**Comment by jimtng** [comment]
> I believe a dimmer is 'ON' if > 0 and 'OFF' if = 0.
> 
> So it tracks for me that the case statements work this way.

Yes this is true. However, this issue concerns the handling of received_command so that the rule knows exactly which command was sent.

If a dimmer item was sent an ON command, I'd like to know that it's actually an OnOffType::ON command being sent, not a PercentType(100).

**Comment by boc-tothefuture** [comment]
@jimtng is that a separate issue from this one?

**Comment by jimtng** [comment]
> @jimtng is that a separate issue from this one?

No, it is the core of this issue. The ability to handle event.command and know precisely the command sent

**Comment by jimtng** [comment]
I just noticed in the docs: https://boc-tothefuture.github.io/openhab-jruby/usage/execution/run/#command-event-properties

It isn't really true at the moment, and it's related to this issue I believe.

Example script:
```ruby
rule 'x' do
  received_command DimmerItem1
  run do |event|
    logger.error('Received Command is ON') if event.command.on?
    logger.error("Received Command: #{event.command}")
  end
end

DimmerItem1.on
DimmerItem1 << 10
```

Both will show `Received Command is ON` which is wrong for the second case.

**Comment by jimtng** [comment]
What I think should happen is this:

```ruby
rule 'command' do
  received_command DimmerItem1
  run do |event|
    if event.command.on?
      logger.error('The command is "ON"') 
    else
      logger.error('The command is NOT "ON"')
    end
  end
end

rule 'state' do
  updated DimmerItem1
  run do |event|
    logger.error('Yes, the state is ON!') if DimmerItem1.on?
  end
end

DimmerItem1 << 10
```

It should log:
```
The command is NOT "ON"
Yes, the state is ON
```

**Comment by ccutrer** [comment]
that's never going to work. if you change it to `event.command == ON`, we could make it work that way (as a breaking change). `event.state` and `event.command` return the same type of object (PercentType) in this case, so we can't have permissive conversions with one usage (when from a command event), but not the other (when from a state event).

**Comment by ccutrer** [comment]
I should probably add that `event.command.eql?(ON)` will currently work how you think it will. `eql?` is the ruby way of saying "is this the same value, _without_ doing any implicit conversions between types". it's usually the same meaning as `==`, but some things implement it (I did, because of all the implicit conversions we do, and things like Float and Integer implement it if you want to make sure an Integer isn't implicitly converted to a Float)

**Comment by jimtng** [comment]
> if you change it to `event.command == ON`, we could make it work that way (as a breaking change)

OK so currently it doesn't work (it will evaluate to true even when the command is PercentType > 0), but it can be made to work. However, it might be a bit confusing from a user's perspective or at least to me, because we are saying that .on? is basically checking for ON state. 

Maybe a DimmerItem should not have supported on?/off?, since it is just a PercentType, and the only time OnOffType is allowed is when it's receiving command? That would probably solve this issue altogether.

It seems that we're mixing ACCEPTED_COMMAND_TYPES with ACCEPTED_DATA_TYPES

Should we allow `DimmerItem1.on` but not `DimmerItem1.on?`

**Comment by ccutrer** [comment]
`DimmerItem#on?` is _extremely_ useful. it allows you to do things like `gLights.select(&:on?).each { ... }` without regard to if the members of the group are actually SwitchItem or DimmerItem. It's also impossible to get rid of. DimmerItem inherits from SwitchItem, where `#on?` is actually defined.

**Comment by ccutrer** [comment]
oh, and I should point out that it's also important to the implementation of `DimmerItem.ensure.on`, which will internally check `state != ON` before sending the `ON` command.
