### ISSUE TITLE
reentrant timer: a case where the timer gets re-entered unintentionally

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#342]
I'm converting my rules to take advantage of the new reentrant timer feature.

In one case, the timer's duration may need to be included as a part of the reentrant_id

Case in point:

```ruby
rule 'send warnings' do
  received_command SwitchItem1
  run do |event|
    if event.command.on?
      [1, 3, 10].each do |secs|
        after(secs.seconds, id: event.item) { logger.info("This is your #{secs} second warning for #{event.item.name}") }
      end
    else
      timers[event.item]&.each(&:cancel)
    end
  end
end
```

This would currently result in only one timer being created, as it would've been 'reentered' 3 times within the same rule execution. As a result, only one warning is logged:
```
This is your 1 second warning
```

the subsequent calls to `after` would merely reschedule the 1sec timer.

**Comment by jimtng** [comment]
I suppose I could provide a unique id, .e.
```ruby
        after(secs.seconds, id: "#{event.item.name} #{secs}") { logger.info("This is your #{secs} second warning for #{event.item.name}") }
```

**Comment by jimtng** [comment]
> I suppose I could provide a unique id, .e.
> 
> ```ruby
>         after(secs.seconds, id: "#{event.item.name} #{secs}") { logger.info("This is your #{secs} second warning for #{event.item.name}") }
> ```

Although this would make cancelling them a bit more difficult, as I can't use `timers[SwitchItem1]&.each` any more

**Comment by boc-tothefuture** [comment]
I think in the first case above what should happen (and doesn't).  Is that it should schedule the timer for 1 second, then rescheduled for 3 seconds, then 10.  If you enter the same after block with a different duration it should reschedule based on the new time..  Just like the timed commands do. 

If you want to uniquely identify a timer it will need a unique ID.  The other option would be to add a 'reentrant:' option that you could set to false.

**Comment by ccutrer** [comment]
I haven't been following this very close, but I'm really glad that you used `id` instead of `reentrant`. I still really hate the terminology `reenter`. Maybe a better term would be "deduplicate"? Reentrancy just has a very specific meaning in computer science (https://en.wikipedia.org/wiki/Reentrancy_(computing)) that even if you apply it to "try to run the same timer block multiple times" would mean "it actually runs multiple times, just safely" and _not_ "you can't run it multiple times".

**Comment by ccutrer** [comment]
oh heh, I actually read this thread now. the `id` is essentially being used as a hash key, and it's super normal in ruby do build up composite keys using arrays. so it would be `after(secs.seconds, id: [event.item, secs]) ...`. still doesn't solve your problem of iterating all timers for a particular item (and is part of why I think we're getting too swiss-army-knife-that-isn't-actually-useful-in-all-situations), but it does clean it up a bit.

**Comment by jimtng** [comment]
> Maybe a better term would be "deduplicate"? Reentrancy just has a very specific meaning in computer science (https://en.wikipedia.org/wiki/Reentrancy_(computing)) that even if you apply it to "try to run the same timer block multiple times" would mean "it actually runs multiple times, just safely" and _not_ "you can't run it multiple times".

Indeed we should probably change the terminology (in the docs). 



> so it would be `after(secs.seconds, id: [event.item, secs]) ...`. still doesn't solve your problem of iterating all timers for a particular item

Something  like:
```ruby
timers.select { |id| id.first == event.item }.each(&:cancel)
```
