### ISSUE TITLE
get_as_state

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#349]
Items support getAsState which can be useful for items like color that accept 3 types of states (switch, dimmer, and hsb).

I am not overjoyed with 
item.get_as_state(OnOffType)

Ideas on how to do that better?

**Comment by jimtng** [comment]
#to_onoff / #to_percent, #to_hsb?

**Comment by ccutrer** [comment]
`GuestCans_Dimmer.state.as(OnOffType)` already naturally works.
