### ISSUE TITLE
MonthDay comparisons

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#377]
Thanks for adding MonthDay! 

I'd like to suggest some additional features:

```ruby
MonthDay.now == '11-05'
MonthDay.now > '11-05'
MonthDay.now.between? '11-01'..'11-05' # this is similar to TimeOfDay.now.between?
```

**Comment by boc-tothefuture** [comment]
Do those first two work?  It implements the spaceship operator and converts from strong to monthday so it should.

**Comment by jimtng** [comment]
The test for `>` works. The test for == always returns false. For today (6th Nov) this should've been true, but it says false

```ruby
logger.error("Test #{MonthDay.now == '11-06'}")
```
