### ISSUE TITLE
Terse rules can't be nested

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#381]
In my motion trigger rule, I created a nested rule in such manner:

```ruby
rule 'xxx' do
  changed Item1
  run { xxx }
  changed Item2 { xxxx } # this is the nested terse rule
end
```

The above doesn't work - the terse rule doesn't result in the creation of another rule.

Using a normal rule however, works:
```ruby
rule 'xxx' do
  changed Item1
  run { xxx }
  rule 'yyy' do
    changed Item2 
    run { yyyy }
  end 
end
```

I understand that nesting rules probably wasn't a part of the original design, so I'm happy to use the second form and happy that it works.

**Comment by ccutrer** [comment]
how is

```ruby
rule 'xxx' do
  changed Item1
  run { xxx }
  rule 'yyy' do
    changed Item2 
    run { yyyy }
  end 
end
```

any different than

```ruby
rule 'xxx' do
  changed Item1
  run { xxx }
end

rule 'yyy' do
  changed Item2 
  run { yyyy }
end 
```
?

Terse rules can definitely not be nested directly inside of a rule definition block as is. I could see a way to achieve it if we integrate more directly into the triggers, so that if a block is given to a trigger function, it knows it's not a trigger for the current rule definition, but for a new terse rule. But what would be the point? I'd be more inclined to override `rule` within a rule definition block to remove the possibility of nesting as in your second example. That just seems super confusing and not useful. _Inside_ if a `run` block we could preserve. Still seems a bit weird to me, but not as obviously something that should be disallowed.

**Comment by boc-tothefuture** [comment]
Nested rules certainly wasn't part of the design and I am not sure what it accomplishes?

**Comment by jimtng** [comment]
I am using nested rule in my motion trigger "dsl" https://community.openhab.org/t/motion-sensor-light-trigger-in-jruby/115911

This allows me to create a set of pseudo rules like this: (Note that this rule's triggers are the motion sensors)

```ruby
rule 'MT: Back Porch' do
  trigger BackPorch_Motion
  only_if { Sun_Elevation.negative? }
  not_if Sleep_Mode
  turn_on BackPorch_Light1, for: 15.minutes
  turn_on BackPorch_Light2, for: 15.minutes
end
```

I then define `turn_on` as a method that defines the run block for the main rule to turn on the light, but also creates a totally separate rule that uses the light itself as the trigger for the rule.
```ruby
  def turn_on(item, for: 2.minutes, manual: 1.hour, debounce: nil, &block)
    run { xxx }
    rule 'yyy' do
      changed YYYY
      run { yyyy }
    end
  end
```

The full code is posted in the link above.

If there's a better way of doing this that avoids nesting, I'd love to know.

**Comment by ccutrer** [comment]
what if you were to do something like this (once `script_loaded` is properly working from #368):

```ruby
motion_items = []

def turn_on(item, for: 2.minutes, manual: 1.hour, debounce: nil, &block)
  motion_items << item
  run { xxx }
end

on_load do
  motion_items.each do |item|
    rule 'yyy' do
      changed YYYY
      run { yyyy }
    end
  end
end

rule 'MT: Back Porch' do
  trigger BackPorch_Motion
  only_if { Sun_Elevation.negative? }
  not_if Sleep_Mode
  turn_on BackPorch_Light1, for: 15.minutes
  turn_on BackPorch_Light2, for: 15.minutes
end
```

this is kind of the exact situation I was envisioning for allowing multiple script loaded hooks. some library implements a DSL of its own that lets you call stuff. then once the script is completely loaded, it can go through everything the DSL did, and define more stuff if it wants. obviously we can't nest that as implemented yet, but a DSL-using-a-DSL-using-a-DSL is probably getting a bit meta

**Comment by ccutrer** [comment]
Btw, I'd consider it a bug that `run` works from within your `turn_on` method (rule configuration methods should _only_ be visible directly within the rule block). of course, fixing _that_ would allow you to do terse rules inside your `turn_on` method, but then you'd lose your run block. I think the way to use it at that point would be:

```ruby
  def turn_on(item, for: 2.minutes, manual: 1.hour, debounce: nil, &block)
    changed item { <inner terse rule run block> }
   # return what you want them to run
    proc { xxx }
  end

rule 'MT: Back Porch' do
  trigger BackPorch_Motion
  only_if { Sun_Elevation.negative? }
  not_if Sleep_Mode
  run &turn_on(BackPorch_Light1, for: 15.minutes)
  run &turn_on(BackPorch_Light2, for: 15.minutes)
end
```

**Comment by ccutrer** [comment]
OR I guess you could add _your_ `turn_on` to `RuleConfig`, and you could do `run`, but not terse rules.

**Comment by jimtng** [comment]
> what if you were to do something like this (once `script_loaded` is properly working from #368):
> 
> ```ruby
> motion_items = []
> 
> def turn_on(item, for: 2.minutes, manual: 1.hour, debounce: nil, &block)
>   motion_items << item
>   run { xxx }
> end
> 
> on_load do
>   motion_items.each do |item|
>     rule 'yyy' do
>       changed YYYY
>       run { yyyy }
>     end
>   end
> end
> 
> rule 'MT: Back Porch' do
>   trigger BackPorch_Motion
>   only_if { Sun_Elevation.negative? }
>   not_if Sleep_Mode
>   turn_on BackPorch_Light1, for: 15.minutes
>   turn_on BackPorch_Light2, for: 15.minutes
> end
> ```

Yes I thought of this possibility but wasn't aware of the script_loaded which is the key to getting it done.



> ```ruby
>   def turn_on(item, for: 2.minutes, manual: 1.hour, debounce: nil, &block)
>     changed item { <inner terse rule run block> }
>    # return what you want them to run
>     proc { xxx }
>   end
> 
> rule 'MT: Back Porch' do
>   trigger BackPorch_Motion
>   only_if { Sun_Elevation.negative? }
>   not_if Sleep_Mode
>   run &turn_on(BackPorch_Light1, for: 15.minutes)
>   run &turn_on(BackPorch_Light2, for: 15.minutes)
> end
> ```

This makes my dsl looks a bit uglier.



> OR I guess you could add _your_ `turn_on` to `RuleConfig`, and you could do `run`, but not terse rules.

If calling `run` shouldn't be done from inside a method like the way I'm doing now, I presume calling `changed` or any of the other triggers shouldn't work from inside a method either? In which case my only option would be to create my `turn_on`, `trigger` and `extender` inside `RuleConfig`. I haven't looked into that but it might be a cleaner way of doing it. I'd still need to use the `script_loaded` for my code-created rules though right?

**Comment by ccutrer** [comment]
> If calling `run` shouldn't be done from inside a method like the way I'm doing now, I presume calling `changed` or any of the other triggers shouldn't work from inside a method either? In which case my only option would be to create my `turn_on`, `trigger` and `extender` inside `RuleConfig`. I haven't looked into that but it might be a cleaner way of doing it. I'd still need to use the `script_loaded` for my code-created rules though right?

correct. the intention is that RuleConfig methods should only be available directly in the rule block. but there's nothing preventing you from adding additional methods to RuleConfig that would then be sibling methods, and _could_ call the other RuleConfig methods.
