### ISSUE TITLE
string_item.rb bug?

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#40]
Inside string_item.rb line 42 (last line in the following excerpt:

```ruby
          def <=>(other)
            case other
            when StringItem
              @string_item.state <=> other.state
            when String
              @number_item.state.to_s <=> other
```

Should that @number_item be @string_item instead?

**Comment by boc-tothefuture** [comment]
There are actually multiple bugs in that code.  I implemented <=> but did not `include comparable` so comparisons (==, <, etc) won't work. 

Next issue is that the Java StringItem class doesn't implement compareTo, so the <=> between the states won't work as intended.  

The underlying java string implements compareTo, which we could use, but we would need to determine the 'sort' order for null and undef. Are they 'less than' or 'greater than' an item with value.

I think this might be a copy/paste error from NumberItem. It may make sense to remove the method entirely.

**Comment by boc-tothefuture** [comment]
I resolved this for now by fixing the copy and paste error.
