### ISSUE TITLE
Switch Items should accept ruby Booleans 

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#400]
Currently you need to convert boolean into ON/OFF
I think intuitively True == ON and False == OFF

So:
```
Squeeze_Home_Audio_A_Power << (ZoneSources.members.any? { |source| source == 6 } ? ON : OFF)
```

Becomes:
```
Squeeze_Home_Audio_A_Power << ZoneSources.members.any? { |source| source == 6 }
```

**Comment by boc-tothefuture** [comment]
FYI - this is implemented in my local branch.

**Comment by doits** [comment]
:+1: is there any PR for this? Otherwise I could prepare one (overriding `SwitchItem#format_type`).

**Comment by ccutrer** [comment]
there's not a PR as of yet, and yes, that's exactly where I was envisioning it getting implemented. one thing I wanted to be careful of is how it interacts with `ensure`. basically `ensure` needs to call `format_type` _before_ doing the comparison with the current state. this will also solve a bug I thought of that ensure would not work with color items when sending an alternative representation.

**Comment by boc-tothefuture** [comment]
This is implemented locally and I am now able to push this up and will do so shortly.

**Comment by boc-tothefuture** [comment]
> :+1: is there any PR for this? Otherwise I could prepare one (overriding `SwitchItem#format_type`). 

I already have a n implementation written and tested.  I couldn't push PRs for a while but I can now and will push it shortly.
