### ISSUE TITLE
re_raise_with_backtrace failed when a Java exception occurred

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#406]
I happened to cause a `Java::JavaLang::ClassCastException` exception in my code, and the `re_raise_with_backtrace` failed with an error:
```
Error during evaluation of script 'file:/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20211120-58372-1z6lli.rb': Error during evaluation of Ruby in /Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-4.14.0/lib/openhab/dsl/rules/rule.rb at line 77: (TypeError) exception class/object expected
```

Do we need to encapsulate the Java exception into a ruby Exception before re-raising it?

**Comment by boc-tothefuture** [comment]
I think this has to do with how we get the caller location.  I fixed that in my local branch.

**Comment by jimtng** [comment]
This error occurred in our test just now.

**Comment by boc-tothefuture** [comment]
> This error occurred in our test just now.

Which test?

**Comment by jimtng** [comment]
> > This error occurred in our test just now.
> 
> Which test?

Just about every failure that happened in the "Actions" tab of this project.

https://github.com/boc-tothefuture/openhab-jruby/runs/4388814035?check_suite_focus=true
https://github.com/boc-tothefuture/openhab-jruby/runs/4388390064?check_suite_focus=true
https://github.com/boc-tothefuture/openhab-jruby/runs/4345987776?check_suite_focus=true

Seems to happen on guards.feature:242 a lot.

Look at Action errors when merging to main.
