### ISSUE TITLE
Allow creation of a rule with no triggers

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#411]
In OpenHAB, you can have a rule with no triggers. 
https://www.openhab.org/javadoc/latest/org/openhab/core/automation/rule

> A Rule with an empty list of Triggers can only be triggered through the RuleRegistry#runNow(String, boolean, java.util.Map) method, or directly executed with the RuleRegistry#runNow(String) method.

It can also be triggered via GUI.

**Comment by boc-tothefuture** [comment]
Ok, right now we just have a check and don't add the rule.  
Should we log a warning?

**Comment by jimtng** [comment]
This would be an easy 2 line change and I've just made a local branch to implement this. But the question is do we want to allow this? 

Having a triggerless rule allow a GUI rule to execute our rule, including the guard clauses. But, I'm wondering who'd bother with GUI rules when they are mixing it with file-based rules, why not just use full file-based rules.

I'm just not sure of its use case.
