### ISSUE TITLE
development environment ignored local libraries when there's a new released version

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#412]
I spent a few hour scratching my head because my branch that's based on 4.14.0 doesn't seem to be applied to the dev environment for cucumber test. 

I eventually discovered that the dev env overwrites the local package with the latest 4.14.1, so my modifications didn't apply.

I had to rebase my branch to 4.14.1

Is this a wanted behaviour?

**Comment by boc-tothefuture** [comment]
I have hit that too. I think it is just the gem loading behavior.  It is pulling the latest version that matches the versioning constraints. 

We could modify the cucumber setup to remove other versions
