### ISSUE TITLE
Github tests seem flakey

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#425]
I often had to re-run test jobs due to some weird non-code related errors. Why is it happening? An example below

![image](https://user-images.githubusercontent.com/2554958/143320282-4112f53b-da58-4ede-911a-f80082415dd8.png)

**Comment by boc-tothefuture** [comment]
The tests are getting less stable.  Have you noticed a pattern?

**Comment by jimtng** [comment]
https://github.com/boc-tothefuture/openhab-jruby/issues/406#issuecomment-984189346

**Comment by jimtng** [comment]
I'm trying to think about what could be causing this error `Could not find 'bundler'`.

**Comment by jimtng** [comment]
Another intermittent error:
https://github.com/boc-tothefuture/openhab-jruby/runs/4830706941?check_suite_focus=true

![image](https://user-images.githubusercontent.com/2554958/149656781-c64a63e7-888d-4f3e-858b-45903cf80ce9.png)

If I re-run the check, it will eventually pass

**Comment by jimtng** [comment]
The error in guard.feature is intermittent, and often, but quite consistently happening right at the same spot. Here it happened again
https://github.com/boc-tothefuture/openhab-jruby/runs/4846789583?check_suite_focus=true

**Comment by boc-tothefuture** [comment]
I have started developing and debugging on my server which is a lot faster than my dev machine. I have noticed we have a race condition (with fast machines) in which our conditions for deploying a rule don't indicate that the rule is fully registered.  

```
2022-01-18 06:56:03.264 [TRACE] [automation.internal.RuleEventFactory] - creating ruleEvent of type: RuleStatusInfoEvent
2022-01-18 06:56:03.264 [TRACE] [automation.internal.RuleEventFactory] - creating ruleEvent of type: RuleStatusInfoEvent
2022-01-18 06:56:03.264 [TRACE] [automation.internal.RuleEventFactory] - creating ruleEvent of type: RuleStatusInfoEvent
2022-01-18 06:56:03.264 [INFO ] [.cucumber_test20220118-229822-cykgv2] - Processing Complete for 8006151d-4b62-4060-a537-a6a5282954eb
```
Even after internal logs from RuleEventFactory indicate a new rule was added and after processing complete is emitted into the log, if I don't sleep I get failures. 

I wonder if this causes some of our intermittent failures in the test pipeline where the build machines might be fast as well.

**Comment by jimtng** [comment]
The error in the screenshot above, indicates that it was expecting the log line to exist, but after waiting for 5 seconds, the log still didn't show up. Unless I've misunderstood, wouldn't that mean that something is not happening, or taking too long. That would be the opposite of running on a fast machine.

**Comment by jimtng** [comment]
I looked into the github action dump file and saw this in the log of the failed guards.feature:263

```
2022-01-16 06:02:49.806 [ERROR] [y.cucumber_test20220116-3128-1tywhza] - Invalid value for MinuteOfHour (valid values 0 - 59): -3 (Java::JavaTime::DateTimeException)
In rule: Log result of between guard
java.time.temporal.ValueRange.checkValidValue(java/time/temporal/ValueRange)
java.time.temporal.ChronoField.checkValidValue(java/time/temporal/ChronoField)
java.time.LocalTime.of(java/time/LocalTime)
jdk.internal.reflect.GeneratedMethodAccessor67.invoke(jdk/internal/reflect/GeneratedMethodAccessor67)
jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl)
java.lang.reflect.Method.invoke(java/lang/reflect/Method)
org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:427)
org.jruby.javasupport.JavaMethod.invokeStaticDirect(org/jruby/javasupport/JavaMethod.java:359)
RUBY.initialize(/home/runner/work/openhab-jruby/openhab-jruby/tmp/openhab/conf/scripts/lib/ruby/gem_home/gems/openhab-scripting-4.28.1/lib/openhab/dsl/time/time_of_day.rb:73)
org.jruby.RubyClass.new(org/jruby/RubyClass.java:886)
org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)
RUBY.<main>(/home/runner/work/openhab-jruby/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20220116-3128-1tywhza.rb:10)
org.jruby.RubyBasicObject.yieldUnder(org/jruby/RubyBasicObject.java:1757)
org.jruby.RubyBasicObject.instance_exec(org/jruby/RubyBasicObject.java:2673)
org.jruby.RubyBasicObject$INVOKER$i$0$3$instance_exec.call(org/jruby/RubyBasicObject$INVOKER$i$0$3$instance_exec.gen)
RUBY.rule(/home/runner/work/openhab-jruby/openhab-jruby/tmp/openhab/conf/scripts/lib/ruby/gem_home/gems/openhab-scripting-4.28.1/lib/openhab/dsl/rules/rule.rb:43)
RUBY.thread_local(/home/runner/work/openhab-jruby/openhab-jruby/tmp/openhab/conf/scripts/lib/ruby/gem_home/gems/openhab-scripting-4.28.1/lib/openhab/core/thread_local.rb:24)
RUBY.rule(/home/runner/work/openhab-jruby/openhab-jruby/tmp/openhab/conf/scripts/lib/ruby/gem_home/gems/openhab-scripting-4.28.1/lib/openhab/dsl/rules/rule.rb:40)
RUBY.<main>(/home/runner/work/openhab-jruby/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20220116-3128-1tywhza.rb:7)
org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:1292)
org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:1296)
org.jruby.embed.internal.EmbedEvalUnitImpl.run(org/jruby/embed/internal/EmbedEvalUnitImpl.java:119)
org.jruby.embed.jsr223.JRubyEngine.doEval(org/jruby/embed/jsr223/JRubyEngine.java:97)
org.jruby.embed.jsr223.JRubyEngine.eval(org/jruby/embed/jsr223/JRubyEngine.java:124)
org.jruby.embed.jsr223.JRubyEngine.eval(org/jruby/embed/jsr223/JRubyEngine.java:150)
org.openhab.core.automation.module.script.internal.ScriptEngineManagerImpl.loadScript(org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java:177)
org.openhab.core.automation.module.script.rulesupport.loader.ScriptFileWatcher.createAndLoad(org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java:231)
org.openhab.core.automation.module.script.rulesupport.loader.ScriptFileWatcher.importFile(org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java:211)
org.openhab.core.automation.module.script.rulesupport.loader.ScriptFileWatcher.lambda$2(org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java:203)
java.util.Optional.ifPresent(java/util/Optional)
org.openhab.core.automation.module.script.rulesupport.loader.ScriptFileWatcher.importFileWhenReady(org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java:201)
org.openhab.core.automation.module.script.rulesupport.loader.ScriptFileWatcher.processWatchEvent(org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java:178)
org.openhab.core.service.WatchQueueReader.run(org/openhab/core/service/WatchQueueReader.java:240)
java.lang.Thread.run(java/lang/Thread)
```

So it's a logic error in the test. When the current minute is < 5, subtract by 5 resulting in a negative minute, which raised an exception. That explains the intermittent-ness of the issue.

Bingo!

I'll do a PR to fix guards.feature

**Comment by boc-tothefuture** [comment]
> The error in the screenshot above, indicates that it was expecting the log line to exist, but after waiting for 5 seconds, the log still didn't show up. Unless I've misunderstood, wouldn't that mean that something is not happening, or taking too long. That would be the opposite of running on a fast machine.

What I am seeing is a race condition:

Working case:
1. New script file detected
2. Script is executed
3. OpenHAB does whatever it does to register triggers w/ items, things, etc.
4. Script Outputs "Processing Complete"
5. Cucumber sends item update
6. Log message written to log
7. Cucumber sees log message

Race condition case I see on my server:
1. New script file detected
2. Script is executed
3. Script Outputs "Processing Complete"
4. Cucumber sends item update
5. **OpenHAB does whatever it does to register triggers w/ items, things, etc.**
6. Nothing written to log because update sent before OpenHAB registered trigger
7. Cucumber times out

**Comment by jimtng** [comment]
Could we make `rule` method to be synchronous, i.e. wait until the rule is registered before returning?

It is conceivable that actual user rule files in production would be sending a command outside the rule, e.g.

```ruby
rule 'test' do
  received_command Item1
  run { ... }
end

Item1 << something
```

If such a race condition exists, the above rule file would not always work as expected.

**Comment by boc-tothefuture** [comment]
I think it is not us or anything we can lock on but I need to look at the code in OpenHAB.
My hunch is that when we call automation_manager.addRule() that method returns before the rule is fully registered in OpenHAB - I am guessing that some part of that registration is asynchronous.   But again, I need to look at the code.

**Comment by jimtng** [comment]
If we were to implement some check / wait before `rule` returns, it would slow down openhab startup, possibly considerably, unless rule files are loaded in parallel, which doesn't seem to be the case afaik. The rule files are loaded alphabetically and synchronously, i.e. the next rule is only loaded after the last one.

**Comment by jimtng** [comment]
I had a quick look. It seems that rules are loaded asynchronously, because it has rule status initializing, etc.

https://github.com/openhab/openhab-core/blob/57ed7ef5a7922db960f135953459d54bb48b078e/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/RuleStatus.java#L76-L96

There's RuleManager::getStatus

**Comment by boc-tothefuture** [comment]
I wonder if we can get that status from the rest API.

**Comment by jimtng** [comment]
I would guess that you could - because MainUI can show rule status. We just need to make sure that all rules are IDLE at the end of "I deploy the rule" step.

**Comment by boc-tothefuture** [comment]
It is in the rest API. I think we could:
1. Edit the library so that when it adds a rule, we log that UID at a trace level.
2. The 'rule deployed' cucumber step, looks for those log entries to get the relevant UIDs and then waits until they are in the 'idle' state.

**Comment by jimtng** [comment]
Sounds good

**Comment by boc-tothefuture** [comment]
Waiting for the idle state did not fix it.

**Comment by jimtng** [comment]
How can the issue be reproduced?

**Comment by boc-tothefuture** [comment]
I can reproduce with any test it on my server if I don't make it sleep 1 second after the log line for 'processing complete for <UID>' is registered.  I just have not been able to check it out why yet.

**Comment by jimtng** [comment]
It seems that the github tests are more stable since the last fix. Have you seen the race condition lately, @boc-tothefuture ?

**Comment by boc-tothefuture** [comment]
I would say they seem more stable, but we have also had less PRs.  Let's close and reopen if we need to.
