### ISSUE TITLE
Using our testing library to test user rules / library

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#429]
Just an idea, if we could use the same cucumber dsl for user rules and/or user library.

**Comment by boc-tothefuture** [comment]
Could you elaborate a bit? .


Would this run on a test system for the user or production?

Would this be packaged as a gem that could be installed as cucumber steps?

**Comment by jimtng** [comment]
I don't have a clear idea how this can/should be implemented. 

I just know from experience that often, little changes to existing rules (in production) could break the functionality and manual testing need to be done to ensure that the rules still function properly.

Having written/formulated tests would help greatly in avoiding surprises.

**Comment by ccutrer** [comment]
I've also had testing in the back of my mind for a while. From creating a completely parallel library that just mocks the entire OH API, to being able to connect a debugger into a live openhab instance, I've had several ideas, but nothing that has jumped out at me as going to be fantastic yet. I just hate how incredibly slow our tests are, but that may just be something we have to live with. Maybe in a "test all _my_ rules" world you copy all the items and rules into openhab _once_, then you just do a bunch of manipulations of items and verify their states. I'm pretty sure most of the slowness is in creating new rule files, and waiting to ensure they've been loaded.

**Comment by jimtng** [comment]
You kinda have to load all the rules at once because part of the problems/bugs could be in how multiple rules could be interacting or be based on the same triggers. Testing individual rules won't catch this.

So basically the tests could just be executed on the production system, it would be like running a "demo mode" on your home automation where it would cause lights to go on and off, things (blinds, gates) to open/close etc. 

I understand that in some cases this may not be desirable e.g. opening external doors/gates, so each test should be done individually.

**Comment by jimtng** [comment]
Just a thought: we could fire up a separate openhab instance, copy all the things, items, rules, addons, from the live instance (maybe do a backup/restore). 

However, the test instance will need to not connect to the real world, so things like mqtt bridge needs to be disabled.  This can be a part of the setup process of the test environment in addition to syncing the things/items/rules/addons/config.

After that, cucumber or rspec tests can be written against it.

This sounds like a separate project on its own.

**Comment by jimtng** [comment]
A dockerised test environment which has its network disabled + no access to the real devices might do the trick

**Comment by ccutrer** [comment]
https://github.com/ccutrer/rspec-openhab-scripting
