### ISSUE TITLE
Timer / after xxx { xxx } error

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#45]
It seems that the `after xxx` cannot be used with a curly braced block, such as:
```
after 10.seconds { SwitchItem << OFF }
```

I received this error:
```
22:50:20.559 [WARN ] [core.internal.scheduler.SchedulerImpl] - Scheduled job failed and stopped
org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `call' for nil:NilClass
Did you mean?  caller
	at RUBY.initialize(/openhab/conf/automation/lib/ruby/lib/openhab/core/dsl/timers.rb:31) ~[?:?]
```

Would it be possible to make it work with curly braces?

**Comment by boc-tothefuture** [comment]
It should.. there is no difference (code wise) in ruby between the two..

I am wondering if its a precedence thing.

does this work?
```
after(10.seconds) { SwitchItem << OFF }
```

**Comment by jimtng** [comment]
> It should.. there is no difference (code wise) in ruby between the two..
> 
> I am wondering if its a precedence thing.
> 
> does this work?
> 
> ```
> after(10.seconds) { SwitchItem << OFF }
> ```

Thank you! Yes, this indeed works! I have been bitten by precedence issues in Ruby a few times, especially with the ternary operator. Thanks for clarifying! This should also go in the documentation somewhere.

**Comment by jimtng** [comment]
This was just my inexperience with Ruby in general.
