### ISSUE TITLE
Change the logger prefix to org.openhab.automation.script

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#464]
Currently the logger prefix jsr223.jruby needs to be manually set to INFO in the karaf console, otherwise the logging would not be visible.  It seems that many new users stumbled on this issue. JS Scripting uses `org.openhab.automation.script` as its logger prefix. Should we change our logger to match?

**Comment by boc-tothefuture** [comment]
The jsr223 prefix is pretty arbitrary, we could change it to match.

**Comment by jimtng** [comment]
The default level for org.openhab.automation.script is TRACE. This may not be desirable for us.

https://github.com/openhab/openhab-distro/blob/31a6a46432a3618f7d8998b39293a6c5320c90cc/launch/app/runtime/log4j2.xml#L91

The only thing set to INFO is `org.openhab`, so if we want things to work "out of the box", we'd need to use `org.openhab.something` but not `org.openhab.automation.script` However, `org.openhab.automation.script` _is_ meant for script logging.

The best solution is to get openhab distro to change `org.openhab.automation.script` to INFO instead of TRACE.

**Comment by jimtng** [comment]
Also we might want to use `org.openhab.automation.script.jruby` as our logging prefix to differentiate from other scripting languages that might be running at the same time.

**Comment by jimtng** [comment]
Some discussions here: https://github.com/openhab/openhab-distro/issues/1362
