### ISSUE TITLE
Item points to a stale instance

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#466]
I came across a weird problem.

I have a rule file that thinks the status of an item was OFF even when it changed to ON.
The only way to make the rule "see" the actual item status was to reload the rule file.

What could be the cause of this problem?

**Comment by jimtng** [comment]
I should add, that I have this as a constant outside of the rule block:

```ruby
SHOWER_LIGHT = { MasterBathRoom_Humidity => Shower_Light, MainBathRoom_Humidity => MainBathRoom_Light_Power }
```

Both `Shower_Light` and `MainBathRoom_Light_Power` didn't return the correct item status inside the rule body. They were referred to as:

```
rule 'x' do
  updated SHOWER_LIGHT.keys
  triggered do |item|
    light = SHOWER_LIGHT[item]
    logger.info("#{light.name}: #{light}")
  end
end
```

I suspect this has something to do with it. However, I've only started noticing this problem since 3.2. The same rule has been running fine in the past.

**Comment by jimtng** [comment]
I believe the cause is this: after the rule was loaded, I might have made some changes to the items file definition that might have caused the items to get 'refreshed' within openhab, which might have resulted in a new instance of the item, meanwhile the rule is still referring to the item's old instance (because the constant is not being re-evaluated).

I guess the moral of the story is only use this form of item constant when the items aren't being tinkered with. When the items definitions are constantly being updated, it's best to dynamically resolve the item inside rule's invocations.

However it makes me wonder about rules' triggers and whether they too would be referring to old items instances and could stop triggering.

**Comment by jimtng** [comment]
> However it makes me wonder about rules' triggers and whether they too would be referring to old items instances and could stop triggering.

I've just realised the answer to this: rules triggers are based on item names as string, so it would continue to work even when the item objects changed.

**Comment by boc-tothefuture** [comment]
Is it the lookup that is stale or the trigger?

**Comment by jimtng** [comment]
> Is it the lookup that is stale or the trigger?

The trigger is not stale.

It isn't the lookup that's stale either. It's the fact that the lookup was done at script loading time is what makes it stale.

**Comment by boc-tothefuture** [comment]
Hmm.  That could be very confusing for users.  I wonder if we should change the implementation so that we aren't returning the OpenHab item for those lookups bit a proxy/delegate object that fetches right before any operations are performed on it.

**Comment by ccutrer** [comment]
I had the same thought. I kinda hate wrapping things unless absolutely necessary, and this would be a good reason to do so. I worry about other things things that would be unavoidable though. Like I have a rule:

```
keypads = things.select { |t| t.thing_type_uid == "mqtt:homie300" && t.channels["keypad#code"] }

rule "Keypad Code Received" do
  channel "keypad#code", thing: keypads
```

no amount of wrapping or delegating is going to fix that code to have rules as new keypads are added or removed.

**Comment by jimtng** [comment]
> I wonder if we should change the implementation so that we aren't returning the OpenHab item for those lookups bit a proxy/delegate object that fetches right before any operations are performed on it.

That would solve the problem I'm having. However, where/when is it going to do the lookup? Almost every call to any of the item's method would require a lookup, so I'm wondering about the impact to performance.

As I said, one way to solve it is to use items' names (string) as the global constant and do a lookup inside the rule, which is basically how I used to do it in Jython before switching over to jruby, i.e.

```
SHOWER_LIGHT = { 'MasterBathRoom_Humidity' => 'Shower_Light', 'MainBathRoom_Humidity' => 'MainBathRoom_Light_Power' }
```

**Comment by boc-tothefuture** [comment]
I doubt we would have any end user visible performance degradation.

Hash lookups are O(1) operations, in the grand scheme of everything that has to happen for a rule to fire I doubt it would be measurable.

**Comment by jimtng** [comment]
Would the proxy object work for resolving the key in this scenario:

```
ASSOCIATED_ITEM = { KeyItem => ValueItem }

rule 'x' do
  changed KeyItem
  triggered do |item|
    value_item = ASSOCIATED_ITEM[item]
  end
end
```

will `item` in triggered do |item| match the hash key inside ASSOCIATED_ITEM?

**Comment by boc-tothefuture** [comment]
I think so.. It appears that item hashcode and equals are [based solely on the name](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java)
