### ISSUE TITLE
add an option to jrubyscripting addon to auto-require 'openhab'

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#475]
Just an idea, I don't use gui scripting myself: If we added an option to jruby.cfg so that the addon adds / evals `require 'openhab'` it would bring the jruby helper library more easily for the gui scripters.

jsscripting addon does this + automatically installing the js helper npm package

**Comment by jimtng** [comment]
Option 1

* Go back to using inline bundler to install gems
* Add an extra syntax to the `gems` option to specify the "require" option to the "gem" command/method: `org.openhab.automation.jrubyscripting:gems=openhab-scripting:openhab=>=4.3.0,foo:file=version,bar` which translates to:
```ruby
gemfile do
  source 'https://rubygems.org'
  gem 'openhab-scripting', '>=4.3.0', require: 'openhab'
  gem 'foo', 'version', require: 'file'
  gem 'bar'
end
```

**Comment by jimtng** [comment]
@boc-tothefuture Should issues related to the addon be discussed in https://github.com/openhab/openhab-addons/issues instead?

**Comment by jimtng** [comment]
Option 2: Add a new configuration setting e.g. `require=foo,bar,moo/cow` which translates to these being eval'ed:
```ruby
require 'foo'
require 'bar'
require 'moo/cow'
```

**Comment by ccutrer** [comment]
Option 1a: add an `openhab-scripting.rb` file in the gem that just `require "openhab"`. That's pretty common when the gem name doesn't exactly match the filename convention of the gem to add a simple require shim so that bundler auto-requiring works. Though I admit I can't remember where we ended up with in the add-on for installing gems; this may not help.

**Comment by jimtng** [comment]
Yes option 1a would greatly simplify it, but then it would not give us the choice of not auto requiring it.

In situations like the httparty issue I think I'd like to have the flexibility so I can require something before openhab and only for certain scripts.

**Comment by ccutrer** [comment]
that's a very good point

**Comment by jimtng** [comment]
Option3: have a checkbox/boolean option to say automatically require gems or not.

We include the openhab-scripting.rb shim as suggested in option 1a.

The code in the addon would use gem bundler if auto require is enabled, or use the current implementation for gem installer when auto-require is not enabled.

The advantage of this option is simplicity for end user with just one extra true/false option

**Comment by ccutrer** [comment]
that seems confusing and error prone to have two different ways to install gems. I'm fine with the checkbox, but it should just add an implicit require, not change how gems are installed

**Comment by jimtng** [comment]
Using one way of installing gems, it would have to stay as is (i.e. not using bundler) so it doesn't auto-require. Then if that checkbox is enabled, the addon would eval a bunch of `require 'gem-name'` statements from the gem list, perhaps with `rescue nil` to suppress any errors should the gem not have any `gem-name` script (like openhab-scripting right now).

Is that what you meant by an implicit require?

**Comment by jimtng** [comment]
Alternatively, to keep it simple, just do auto-require with bundler, and any issues caused by incompatibilities would have to be dealt with as they come.

This would be option 3:
- Use bundler installer
- Add openhab-scripting.rb shim so bundler will auto-require

**Comment by ccutrer** [comment]
yup. I was meaning "if we also have a 'requires' list config option, and a 'auto-require-openhab' checkbox config option, the latter would implicitly add another entry to the former at runtime"

**Comment by jimtng** [comment]
As a bonus to all this, even file-based rules won't have to have `require 'openhab'` anymore! If that's the way going forward, `openhab.rb` could be the shim instead and the `openhab-scripting.rb` be made the actual main script.

**Comment by jimtng** [comment]
> yup. I was meaning "if we also have a 'requires' list config option, and a 'auto-require-openhab' checkbox config option, the latter would implicitly add another entry to the former at runtime"

This would add 2 extra configuration options and it would make openhab-scripting a special case

**Comment by jimtng** [comment]
I've just realised #389: bundler installer doesn't upgrade the gems. So scrap options 1 and 4 . Back to adding a manual require 'gemname'

**Comment by jimtng** [comment]
I'm going with option 2. Here's a test jar with some description of how to set it up
https://github.com/jimtng/openhab-addons/releases/tag/jrubyscripting-require-v0.0.1

**Comment by jimtng** [comment]
![image](https://user-images.githubusercontent.com/2554958/155736013-74705de0-c176-4388-b4a1-d06cab7be29e.png)

**Comment by jimtng** [comment]
I've rearranged this configuration screen. The "advanced" works now and will hide the System properties. Also added the description about gem_home/rubylib default.

![image](https://user-images.githubusercontent.com/2554958/155740848-6b1fe3a1-12bb-46a9-a388-0016b8a7a0c6.png)

**Comment by jimtng** [comment]
https://github.com/openhab/openhab-addons/pull/12381

This makes it very nice to use openhab-scripting from GUI rules, both as the action or as condition.

**Comment by jimtng** [comment]
This has been merged into openhab-addon
