### ISSUE TITLE
QuantityType against a string range

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#487]
Can/should we make this to work?

```ruby
('2°C'..'4°C').include?(Dimensioned_Number_Item)
```

Currently it doesn't work. One has to do this instead:
```ruby
(2|'°C'..4|'°C').include?(Dimensioned_Number_Item)
```

**Comment by boc-tothefuture** [comment]
I think it should, yes.

**Comment by jimtng** [comment]
I had a quick look inside string.rb, but it seems a bit tricky (for me) to implement this string-of-quantity range. I found an easier way to do it that is currently already supported:

```ruby
Dimensioned_Number_Item.between?('2°C', '4°C')
```

Although I don't know how to achieve the same as a range that excludes the end like '2°C'...'4°C' using `between?`, but it's not important for me right now.

**Comment by jimtng** [comment]
Hmm... I didn't realise that #include? and #cover? are different. This post explains the difference https://stackoverflow.com/questions/21608935/what-is-the-difference-between-rangeinclude-and-rangecover

#cover? works fine with string range against QuantityType. I wrote a test for it but not sure if it's necessary to be included in our official tests.

```
  Scenario Outline: QuantityType can be compared with a string range
    Given code in a rules file
      """
      quantity = <quantity>|'<unit>'
      logger.info("quantity is in range? #{(<range>).cover?(quantity)}")
      """
    When I deploy the rules file
    Then It should log "quantity is in range? <result>" within 5 seconds
    Examples:
      | quantity | unit | range          | result |
      | 32       | °F   | '5°C'..'40°C'  | false  |
      | 5        | °C   | '5°C'..'10°C'  | true   |
      | 41       | °F   | '5°C'..'10°C'  | true   |
      | 12       | °C   | '5°C'..'10°C'  | false  |
      | 100      | °C   | '5°F'..'200°F' | false  |
```

**Comment by jimtng** [comment]
Perhaps we should mention this in our docs - for the benefit of noobs like me.

**Comment by jimtng** [comment]
I've pushed (accidentally) the doc change that mentions #cover?
