### ISSUE TITLE
refactor commits don't change the version number

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#497]
It seems that the breaking change in #489 didn't result in a new version number. It didn't even make it to the changelog

**Comment by boc-tothefuture** [comment]
I am guessing that is intentional as a refactor, in theory doesn't break the API compatibility.  Not sure if we can modify that behavior.

**Comment by jimtng** [comment]
What tag should be used for a change that isn't a fix but not a feature either?

**Comment by jimtng** [comment]
I will use fix/feat in the future
