### ISSUE TITLE
Integrating PersistenceExtensions into items

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#50]
I feel there is an opportunity to include persistence extensions (if it's available on the openhab environment) into JRuby items, so that instead of:

```ruby
PersistenceExtensions.averageSince(NumberItem1, ZonedDateTime.now().minusHours(1), 'influxdb')
```

we could do something more elegant, e.g.

```ruby
NumberItem1.average_since(......)
```

I'm not yet familiar with what to use for date/time in Ruby though, and it would need to eventually translate into java's ZonedDateTime to pass to the actual PersistenceExtensions.

**Comment by boc-tothefuture** [comment]
I agree, should probably be part of the Item.

It might mean we have to modify the changes down to numerics (5.minutes) etc to be more generic.  The built into ruby Time and DateTime classes aren't that great (IMO), the (newer) java ones are better.  

So we would have to decide do we add a thin layer around the Java ones or just use the ruby ones and convert.  

I don't know the answer without diving a bit deeper.

**Comment by jimtng** [comment]
```ruby
NumberItem1.average_since -5.hours
NumberItem1.average_since MIDNIGHT 
NumberItem1.average_since Time_instance
NumberItem1.average_since ZonedDateTime_instance
```

Should we import ZonedDateTime by default so we don't have to have java_import java.time.ZonedDateTime ?

**Comment by jimtng** [comment]
Waiting for the metadata (osgi) branch being merged, and if the items are going to be refactored from monkey patching to delegate, this feature will also need to wait for the refactoring.
