### ISSUE TITLE
changed trigger with range doesn't support string based quantity

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#503]
This doesn't work:
(UPDATED)
```
   Scenario Outline: Changed support ranges with string quantity
    Given items:
      | type         | name       | state     |
      | Number:Power | Item_Power | <initial> |
    And a rule:
      """
      rule 'Execute rule with range conditions' do
        changed Item_Power, <conditions>
        run { |event| logger.info("Item Power: Changed from #{event.was} to #{event.state}") }
      end
      Item_Power << '<change>'
      """
    When I deploy the rule
    Then It <should> log "Item Power: Changed from <initial> to <change>" within 5 seconds
    Examples: From range
      | initial | conditions          | change | should |
      | 0 W     | from: '0 W'..'10 W' | 14 W   | should |
```

**Comment by boc-tothefuture** [comment]
Is this the same issue as #487 ?

**Comment by jimtng** [comment]
I'm guessing it might be the same. I haven't looked into the code.

**Comment by jimtng** [comment]
@boc-tothefuture Perhaps the range test should use `#cover?` instead of `#include?` ? 

See https://github.com/boc-tothefuture/openhab-jruby/issues/487#issuecomment-1018068959

**Comment by boc-tothefuture** [comment]
Makes sense.  I guess the tradeoff would be if we ever wanted ranges they were enumerable based we would need to figure that out.  The only ones I can think of would be thing states.

**Comment by jimtng** [comment]
Could you give an example of this range with thing states?

**Comment by jimtng** [comment]
My original cucumber test in the first post above had an error. I've updated the post with a correct/tested one. It failed with #include? and passed with #cover? https://github.com/boc-tothefuture/openhab-jruby/blob/bb562a49acb203625a5cf13e1b6d9a8f1638ce5a/lib/openhab/dsl/rules/triggers/conditions/proc.rb#L43

**Comment by boc-tothefuture** [comment]
> Could you give an example of this range with thing states?

Without deeply looking:
```
rule 'Something is offline' do
   changed things['foo'], :from => :online, :to = OFFLINE...ONLINE
   run { logger.error "foo is not available" }
end
```
We don't support that now, so it is all theoretical.  I am fine with moving to cover? since it does fix the cases we care about currently.

**Comment by jimtng** [comment]
I tried this out. 

* ONLINE/OFFLINE is not defined / available. It is not a part of the default scope from openhab: https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java

Instead, we need to use `ThingStatus::OFFLINE...ThingStatus::ONLINE`

* When #include? is used, this rule will cause:
```
Caused by: org.jruby.exceptions.TypeError: (TypeError) can't iterate from Java::OrgOpenhabCoreThing::ThingStatus
```

I guess it's because ThingStatus is not an enumerable?

* When #cover? is used, it won't match
