### ISSUE TITLE
Persistence methods caused an NPE

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#511]
This code caused an NPE:
```ruby
Weather_Current_Rain.sum_since(24.hours)
```

It seems to happen inside `OpenHAB::DSL::Items::Persistence::quantify`

**Comment by ccutrer** [comment]
How is that item defined?

**Comment by jimtng** [comment]
```
Number:Length            Weather_Current_Rain                         "Rain"                                 <Rain>                                     {channel="openweathermap:onecall:bridge:local:current#rain"}
```

**Comment by jimtng** [comment]
Since the item itself doesn't specify a particular unit, its unit is `m` for meter. This is returned by `Weather_Current_Rain.unit.to_s` # => 'm'

However, it seems that the binding is setting the value to 'mm', as evidenced by:
`Weather_Current_Rain.to_s` # => '4 mm'

The data being persisted into influxdb is in 'mm' as well, although I think influxdb doesn't store the unit, but it stores the numbers in what seems to be in mm, i.e. it stores it as 4 instead of 0.004. So where do we get this 'mm' from, in order to feed it to QuantityType's constructor in `#quantify`?

**Comment by jimtng** [comment]
It appears that persistence (at least influxdb) doesn't care about UoM and it doesn't do any conversions. It simply persists the value regardless of unit.

So if you have an item:
```
Number:Power Power "Power [%.1 W]"
```

With persistence strategy everyChange

Code:
```
Power.update '1 kW'
Power.update '2 W'
```

It will simply store the values `1` and `2` into the influxdb, and calling Power.sum_since(something) will return `3` and not 1002 (in the case of W) or 1.002 (in the case of kW)

It seems to be the user's responsibility to make sure that the unit of the data is always consistent. 

Based on this, we cannot really deduce the persistence data's unit based on the item's stateDescription/format, nor on the last state, unless it is always updated using the same unit.

**Comment by ccutrer** [comment]
... yeah. There are several issues with OpenHAB core with UoM. This thread (and GitHub issues it links to) has some details: https://community.openhab.org/t/mqtt-binding-and-units-of-measurement/127026.
