### ISSUE TITLE
accidentally committed / pushed to the wrong repo

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#515]
@boc-tothefuture Ooops sorry I accidentally committed and pushed to the wrong repo here https://github.com/boc-tothefuture/openhab-jruby/commit/a36f0e3478e3f6f856227b7acd9dccacd69bbcb8

What can be done to revert it?

**Comment by boc-tothefuture** [comment]
Is it mostly doc updates?

**Comment by jimtng** [comment]
Yes it's just a doc update. I used the "Publish Branch" button on vscode - I guess I don't understand its exact behaviour, because sometimes it works and publishes to the correct remote. The more foolproof way is using the menu item "Push to..." which will always ask for which remote to publish to.
