### ISSUE TITLE
How to set a const in the rule execution scope?

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#522]
I'm trying to replace the ZonedDateTime from java to ruby class but even if I replaced the global scope, the ZonedDateTime class inside the run context is still the java class.

This problem is solved by the updated binding, but I don't understand how it fixes it. The updated binding simply does an eval of java_import, but simply calling java_import at the top level still won't fix the ZonedDateTime inside the run context.

```
require 'openhab'
java_import java.time.ZonedDateTime

rule 'test' do
  changed DateTimeItem1
  run { logger.info(ZonedDateTime.now.to_s) } # this here will still refer to the java class, and thus caused an error
end
DateTimeItem1 << Time.now
```

Another thing: the run context for the rule execution triggered by on_start is different to the context when it's triggered by other actual openhab triggers.

**Comment by boc-tothefuture** [comment]
If you do the java_import inside the run block does it work?

**Comment by jimtng** [comment]
Yes it works if I do the java_import inside the run block
