### ISSUE TITLE
Conflict with httparty

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#523]
My script doesn't run after I require 'httparty'

Example:
```ruby
require 'openhab'
logger.info('Before httparty')
require 'httparty'
logger.info('After httparty')
```

It will log `Before httparty` but not `After httparty`

My script seems to work fine if I put the require httparty line before require openhab. I haven't yet tested whether this will break httparty, as I haven't started using it.

Why is this happening though?

**Comment by boc-tothefuture** [comment]
I can't think of anything that would conflict.

**Comment by ccutrer** [comment]
That's a great question. I use activesupport in my rules, and I remember having similar problems when I first added it. I ended up only requiring the couple core extensions I wanted, and those worked, so I didn't troubleshoot more, but it would be great to get to the bottom of it.

**Comment by jimtng** [comment]
I have a similar conflict with the "koala" gem too. I also had to put the require line before openhab.

**Comment by jimtng** [comment]
This issue will become important if we want to get the addon to add a `require`, which will require `openhab` ahead of others.
