### ISSUE TITLE
stop aliasing Timer as a top level constant

### ISSUE THREAD

**Issue by ccutrer** [boc-tothefuture/openhab-jruby#530]
We have a [scenario](https://github.com/boc-tothefuture/openhab-jruby/blob/main/features/timer.feature#L159) that ensure you can access `Timer` as a top-level constant, but I propose we remove that scenario, and stop supporting that. `Timer` is a very generic name, easily conflicting with other gems (like we had with `Logger`), and I don't see the need for it to be accessed like that. If you want to access the class, `OpenHAB::DSL::Timer` is clearer what you're accessing, or `after` is easy to use as a top-level DSL method. For easier transition from the OpenHAB rules DSL, we might consider a `create_timer` alias for `after`, as that seems closer to the `createTimer` method than `Timer.new` is.

**Comment by jimtng** [comment]
@boc-tothefuture wdyt? I can create a PR if this is agreed.

**Comment by boc-tothefuture** [comment]
Agree and also like the alias of create_timer
