### ISSUE TITLE
NumberItem|'W' returns true when NumberItem is NULL

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#537]
Strange result:

```
NumberItem1.update NULL
NumberItem1 | 'W' # => true
```

**Comment by jimtng** [comment]
It is because | is delegated to :state, which when the item's state is NULL, #state is nil. 
```
irb(main):046:0> nil | 'W'
=> true
```

**Comment by ccutrer** [comment]
What would we expect to happen here? A NoMethodError? Just return nil?

**Comment by jimtng** [comment]
I think returning nil might be the way to go... wdyt?
What should happen to the arithmetic operators in this case?

**Comment by jimtng** [comment]
This essentially stemmed from my laziness to check for null. 

Perhaps there should be a method that gives me a "default" state when it's null, similar to Java's `Optional.ofNullable(something).orElse(default_value)`

Maybe `NumberItem1.or_else('0 W')|'W'`
or `NumberItem1.or_else(0)|'W'`

What do you think of `or_else`, or else, any better ideas for a better name, or is there an idiomatic Ruby way of dealing with this?

**Comment by ccutrer** [comment]
`(thing_that_might_be_nil || default_value)` is the idiomatic way to do this in Ruby. Except that doesn't work in this case if you only refer to the item, and not its state, and are relying on one of the methods that delegates to state

**Comment by jimtng** [comment]
In fact I think this or_else / if_null / if_undef would be a nice addition to openhab-core

**Comment by jimtng** [comment]
> `(thing_that_might_be_nil || default_value)` is the idiomatic way to do this in Ruby. Except that doesn't work in this case if you only refer to the item

Indeed, that's the problem.

**Comment by jimtng** [comment]
So: `(NumberItem.state || 0)|'W'`

**Comment by ccutrer** [comment]
Heh. If that offends you, you can always call || and | as a normal method: `NumberItem.state.||(0).|('W').format`

Lol that looks terrible. Question - why aren't you using a NumberItem:Energy with the format string already in the description. Then you can just do `"message: #{NumberItem}"`. The string interpolation will call to_s on the item, which formats according to the item's description string, and you've already given it the units. You may want to format NULL differently though, which will take a little work, but still less than you're doing now.

**Comment by jimtng** [comment]
Now why didn't I think of that! 

My Item was declared as Watt: `Number:Power Solar_AC_Power "Solar Power [%.2f W]" `
Because in some other places I want to display it in Watt if the value is < 1000W and in KW when the value is >= 1kW.

But I should indeed review this and maybe just have the spaghetti conversion code in those areas and default the item to kW for this particular part of the code.

Strangely the format specifier (the decimal points) in the item label doesn't seem to be honored.

**Comment by jimtng** [comment]
NumberItem.state.||(0) doesn't work when NumberItem.state = nil.

```
irb(main):055:0> a = nil
=> nil
irb(main):056:0> a.||(0)
Traceback (most recent call last):
        3: from /Users/jimmy/.rbenv/versions/2.6.8/bin/irb:23:in `<main>'
        2: from /Users/jimmy/.rbenv/versions/2.6.8/bin/irb:23:in `load'
        1: from /Users/jimmy/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
SyntaxError ((irb):56: syntax error, unexpected ||)
a.||(0)
  ^~
```

**Comment by ccutrer** [comment]
> Because in some other places I want to display it in Watt if the value is < 1000W and in KW when the value is >= 1kW.

That's an excellent point. OpenHAB's formatting does _not_ support auto-ranging, which does kind of bother me in my basic UI sitemap for exactly the Power dimension. I know the underlying units libraries in java are fantastic for easily being able to adjust the multiplier.

**Comment by ccutrer** [comment]
> NumberItem.state.||(0) doesn't work when NumberItem.state = nil.
> 
> 
> 
> ```
> 
> irb(main):055:0> a = nil
> 
> => nil
> 
> irb(main):056:0> a.||(0)
> 
> Traceback (most recent call last):
> 
>         3: from /Users/jimmy/.rbenv/versions/2.6.8/bin/irb:23:in `<main>'
> 
>         2: from /Users/jimmy/.rbenv/versions/2.6.8/bin/irb:23:in `load'
> 
>         1: from /Users/jimmy/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
> 
> SyntaxError ((irb):56: syntax error, unexpected ||)
> 
> a.||(0)
> 
>   ^~
> 
> ```

:(

Well, next is using send with a symbol, but that's just putting salt in a wound of this horrible syntax

**Comment by jimtng** [comment]
> OpenHAB's formatting does _not_ support auto-ranging

Are you aware of any library that does auto-ranging? I'm wondering if it would be a good candidate for addition into openhab, expanding the formatting syntax. I just don't want to reinvent the wheel if something is already out there.

`%.2f %auto_unit%` ? The fussy me would want to specify have 2 decimal points for kW,MW but no decimal points for W. Wondering how to best express that in the format string.

**Comment by ccutrer** [comment]
https://api.rubyonrails.org/classes/ActiveSupport/NumericWithFormat.html does it for file sizes, but not power ratings. Dunno if it's worth building off that.
