### ISSUE TITLE
Package and distribute this library as a Ruby Gem

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#55]
Distribute this library as a RubyGem

This requires updating the OpenHAB JRuby implementation to accept as a configuration item a list of gems which get installed.

This should make installation, upgrade, etc much easier as user can just specify this gem at a specific version and it would be installed.

Additionally, this means this gem could start relying on other gems as part of its function.  For example, it could rely on the time of day gem rather than repeat some of its functionality.

**Comment by jimtng** [comment]
This is awesome!
