### ISSUE TITLE
Ruby Basics docs

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#555]
Proposal: have a ruby basics section on the docs. This will get potential openhab scripters who aren't familiar with Ruby to get up and running quickly without having to look around elsewhere.

Mentioned in #157 

I've written the following from scratch, so it might have some errors.

**Comment by jimtng** [comment]
# Ruby Basics

The OpenHAB JRuby scripting automation is based on the [JRuby](https://www.jruby.org/) implementation of the [Ruby](https://www.ruby-lang.org/) language. This page offers a quick overview of Ruby to help you get started writing rules. However, it is by no means comprehensive. 
A wealth of information can be found on [Ruby's web site](https://www.ruby-lang.org/en/documentation/).


## Data Types

In Ruby, everything is an object, even primitive types such as numbers and strings. For example, `1` as a number is an object
and has all the methods for the [Integer class](https://ruby-doc.org/core-2.6/Integer.html).

It is useful to get to know the basic data types that we will often encounter:
* [Integer](https://ruby-doc.org/core-2.6/Integer.html) - e.g. `1`, `-3`, etc.
* [Floating Point](https://ruby-doc.org/core-2.6/Float.html) - e.g. `3.5`
* [String](https://ruby-doc.org/core-2.6/String.html) -
  String literals in Ruby can be enclosed with double quotes, or single quotes. Strings enclosed by double quotes can 
  contain variables and expressions that are enclosed with `#{}`. For example: `"Hi my name is #{name_variable}"`. The String class offers a plethora of useful methods to operate on and manipulate strings.
* [Array](https://ruby-doc.org/core-2.6/Array.html) - example: `[1, 2, 'foo', AnotherObject]`
* [Hash](https://ruby-doc.org/core-2.6/Hash.html) - example: `{ 'key1' => 'value', 'key2' => 'value' }`
* [Symbol](https://ruby-doc.org/core-2.6/Symbol.html) - example: `:iamasymbol`

## Variables

* In Ruby, variables usually use `lower_case` with words separated with an underscore.
* Uppercase identifiers are constants, e.g.  `NAMES`
* Variable whose names start with `$` are global variables, e.g. `$i_am_global`.
* Variable whose names start with `@` are instance variables, e.g. `@instance_variable`.
* Local variables are just plain names that starts with a lower case, e.g. `local_var`.
  
## Control Expressions

Ruby supports various [control expressions](https://ruby-doc.org/core-2.6.8/doc/syntax/control_expressions_rdoc.html) such as `if/else`, `ternary operator`, `case`, etc.

Example:
```ruby
if a
  # do something here
elsif b
  # something else
else 
  # something here
end

# modifier if form
a = b if c == 5

# ternary operator
a = b == 5 ? 'five' : 'other'

# case/when similar to the switch() { case... } in c / java.
rule 'x' do
  received_command DimmerItem1
  run do |event|
    case event.command
    when OFF
      Light1.off
      Light2.off
    when 0...50
      Light1.on
      Light2.off
    when 50..100, ON
      Light1.on
      Light2.on
    end
  end
end
```

## Loops

While Ruby supports the traditional `for` and `while` loop, they are rarely used. 
Ruby objects such as array, enumerable, hash, set, etc. provide a plethora of methods to
achieve the same thing in a more "Ruby" way.

### Examples

```ruby
array = [1, 2, 3]
array.each do |elem|
  logger.info("Element: #{elem}")
end

array.each_with_index do |elem, index|
  logger.info("Element #{index}: #{elem}")
end

SWITCH_TO_LIGHT_HASH = { Switch1: Light1, Switch2: Light2 }

SWITCH_TO_LIGHT_HASH.each do |switch, light|
  logger.info "#{switch.name} => #{light.name}"
end

rule 'turn light on' do
  changed Switches.members
  triggered do |item|
    SWITCH_TO_LIGHT_HASH[item]&.command item.state
  end
end
```

## Blocks

Multi-line blocks in Ruby are enclosed in a `do` .. `end` pair and single line blocks are enclosed with braces `{` .. `}`. You have encountered blocks in the examples above.
Rules are implemented in a block:

```ruby
rule 'rulename' do
  ...
end
```

The execution part is also in a block, inside the run block:
```ruby
rule 'rulename' do
  changed Item1
  run do 
    ...
  end
end
```


### Block arguments

Blocks can receive arguments which are passed by its caller. We will often encounter this in a [run]({{ site.baseurl }}{% link usage/execution/run.md %}) and [triggered]({{ site.baseurl }}{% link usage/execution/triggered.md %}) blocks.

```ruby
rule 'name' do
  changed Switches.members
  run do |event|
    # do something based on the event argument
  end
end
```

## Some Gotchas

To exit early from a block, use `next` instead of `return`.

```ruby
rule 'rule name' do
  changed Item1
  run do 
    next if Item1.off? # exit early

    Item2.on # Turn on Item2 if Item1 turned on
    # Do other things
  end
end
```

In Ruby, parentheses are optional when calling a method. However, when calling a method with arguments and a single-line block, 
the parentheses must be used. Example:

```ruby
after(5.seconds) {  }

after(5.seconds) do
  # ...
end

after 5.seconds do
  # parentheses aren't a must before a do..end block
end

# the following example will cause an error
after 5.seconds { }
```



Happy coding!

**Comment by boc-tothefuture** [comment]
I think this is great!  

Two minor suggestions: 
1.  Link to the [ruby style guide](https://github.com/rubocop/ruby-style-guide)
2.  Mention Rubocop and how to use it?
