### ISSUE TITLE
Update method names for logging checks

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#569]
As noted in #567 the logging names should change from the java style `is_info_enabled?` to `info?`, etc.

**Comment by jimtng** [comment]
My mistake - currently it is called `info_enabled?` not `is_info_enabled?` like I wrote in the 'logger' doc page. Should they still be renamed to `info?`

**Comment by boc-tothefuture** [comment]
I think so.
