### ISSUE TITLE
lib path: core / personal 

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#59]
I would suggest the following directory structure:
```
conf/automation/lib/ruby
|
+- core 
|  |
|  +- openhab
|     |
|     + core/dsl
|     ...
|
+- personal <-- for personal libraries 
```

Change
```
export RUBYLIB=<openhab_base_dir>/conf/automation/lib/ruby/lib
```
to:
```
export RUBYLIB=<openhab_base_dir>/conf/automation/lib/ruby/core
```
The above change can be made without affecting anything else. However, for personal libraries to go into
```
<openhab_base_dir>/conf/automation/lib/ruby/personal
```

This would require changes in patch_load_path.rb. I would propose this:
```ruby
module PatchLoadPath
  lib_path = File.realpath(File.join(__dir__, '..'))
  $LOAD_PATH << lib_path unless $LOAD_PATH.include?(lib_path)
  ruby_path = File.realpath(File.join(lib_path, '../..'))
  $LOAD_PATH << ruby_path unless $LOAD_PATH.include?(ruby_path)
end
```

Happy to make a PR for it, if nobody has any objections.

The resulting $LOAD_PATH is:
```
["/openhab/conf/automation/lib/ruby/core", 
"uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/gems/did_you_mean-1.2.0/lib", 
"/openhab/conf/automation/lib/ruby/gem_home/gems/bundler-2.1.4/lib", 
"uri:classloader:/META-INF/jruby.home/lib/ruby/2.5/site_ruby", 
"uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib", 
"/openhab/conf/automation/lib/ruby/core/openhab",
"/openhab/conf/automation/lib/ruby"]
```

I wonder why we need both of these in the LOAD_PATH
* `/openhab/conf/automation/lib/ruby/core`
* `/openhab/conf/automation/lib/ruby/core/openhab`

**Comment by boc-tothefuture** [comment]
I am not opposed. But if we move this to a gem we wouldn't need this outside the gem path. 
I was modeling it on the jython path structure (unless I made a mistake).

**Comment by jimtng** [comment]
> I am not opposed. But if we move this to a gem we wouldn't need this outside the gem path.

In that case the only thing that matters would be the path for the personal libraries.

**Comment by jimtng** [comment]
Right now I am still wondering about how to maintain my own personal ruby library. It's just a matter of adding the load path for `<CONF>/automation/lib/ruby/personal` but I'm not sure where is the best place to set it. Perhaps it should be done in the jruby.cfg to be set by jruby binding?

**Comment by pacive** [comment]
Was just thinking about this too. For me it would be ok with a hard-coded `<CONF>/automation/lib/ruby/personal`. It's what would be most consistent with the other scripting addons.

**Comment by boc-tothefuture** [comment]
We can add RUBY_LIB to the jruby.cfg to support this.

**Comment by jimtng** [comment]
> We can add RUBY_LIB to the jruby.cfg to support this.

Is this currently supported? I tried this inside jruby.cfg but it didn't work:
```
org.openhab.automation.jrubyscripting:RUBY_LIB=/openhab/conf/automation/lib/ruby/personal
```

**Comment by boc-tothefuture** [comment]
No, i will have to add it.

**Comment by pacive** [comment]
In the meantime, it's possible to do:
```ruby
require '/full/path/to/script/file'
```

**Comment by boc-tothefuture** [comment]
The jar is updated, let me know if it works.

**Comment by jimtng** [comment]
I tried the latest jar
```
Initialized a custom ScriptEngineFactory for JSR 223 JRuby Engine (9.2.14.0): supports ruby (jruby 9.2.14.0) with file extensions [rb], names [ruby, jruby], and mimetypes [application/x-ruby]
```

What's the syntax in jruby.cfg? I tried these below:
```
org.openhab.automation.jrubyscripting:RUBYLIB=/openhab/conf/automation/lib/ruby/personal
org.openhab.automation.jrubyscripting:RUBY_LIB=/openhab/conf/automation/lib/ruby/personal
org.openhab.automation.jrubyscripting:rubylib=/openhab/conf/automation/lib/ruby/personal
org.openhab.automation.jrubyscripting:ruby_lib=/openhab/conf/automation/lib/ruby/personal
```

I assume that this would append it to `$LOAD_PATH`, so I checked using `logger.info $LOAD_PATH`

**Comment by jimtng** [comment]
ping @boc-tothefuture what's the syntax in jruby.cfg? Is the binding source code publicly available?

**Comment by boc-tothefuture** [comment]
Code is here:
https://github.com/boc-tothefuture/openhab2-addons/tree/jruby/bundles/org.openhab.automation.jrubyscripting

`org.openhab.automation.jrubyscripting:ruby_lib=/openhab/conf/automation/lib/ruby/personal`
should be the one that works.

**Comment by jimtng** [comment]
> `org.openhab.automation.jrubyscripting:ruby_lib=/openhab/conf/automation/lib/ruby/personal`
> should be the one that works.

It doesn't seem to work

I created a file /openhab/conf/automation/lib/ruby/personal/openuv.rb

then in my script /openhab/conf/automation/jsr223/ruby/personal/uv.rb I have:
```
require 'openuv'
```

```
00:05:07.524 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/ruby/personal/uv.rb': org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- openuv
```

This is my jruby.cfg:
```
org.openhab.automation.jrubyscripting:ruby_lib=/openhab/conf/automation/lib/ruby/personal
org.openhab.automation.jrubyscripting:gem_home=/openhab/conf/automation/lib/ruby/gem_home
org.openhab.automation.jrubyscripting:gems=openhab-scripting=~>3.0
```

```
openhab> bundle:list -s | grep ruby
208 │ Active │  80 │ 3.1.0.202102261344      │ org.openhab.automation.jrubyscripting
```

**Comment by pacive** [comment]
Same thing for me:
```
openhab> config:list | grep -A 7 jruby
Pid:            org.openhab.automation.jrubyscripting
BundleLocation: null
Properties:
   gem_home = /etc/openhab/automation/lib/ruby/gem_home
   gems = openhab-scripting=~>3.0
   ruby_lib = /etc/openhab/automation/lib/ruby/personal
   service.pid = org.openhab.automation.jrubyscripting
```
But `require`-ing files from there doesn't work

**Comment by jimtng** [comment]
The environment variable should be `RUBYLIB` without an underscore. I tried this and recompiled the jar, but it still doesn't work.

It works if I set the environment variable inside my docker-compose.yaml (running openhab inside docker)

**Comment by ccutrer** [comment]
This was fixed by #267

**Comment by jimtng** [comment]
FWIW, I found that RUBYLIB environment variable in my docker-compose.yaml works too

**Comment by jimtng** [comment]
@boc-tothefuture, @ccutrer, I've submitted a PR for the addon that includes what load_path.rb does. This would make it work for GUI users as well. 

https://github.com/openhab/openhab-addons/pull/12123

So that the addon that ships with OH 3.2.0 continue to work, our load_path.rb will still be required.

**Comment by jimtng** [comment]
FYI [The PR](https://github.com/openhab/openhab-addons/pull/12123) has been merged
