### ISSUE TITLE
Document how to setup development environment for this project

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#62]

**Comment by boc-tothefuture** [comment]
@jimtng I took a pass at this [here](https://boc-tothefuture.github.io/openhab-jruby/contributing/) I would appreciate any feedback.

**Comment by boc-tothefuture** [comment]
@jimtng  - could you take a look at the above message and let me know if you think we can close this now?

**Comment by boc-tothefuture** [comment]
@jimtng - gentle poke

**Comment by jimtng** [comment]
sorry I have overlooked this.

I've just read that doc page, and learned new things :)
Just one thing sounded weird:
> Lint your code with bundle exec rake lint and ensure you **have created** any Rubocop or cuke lint violations

**Comment by boc-tothefuture** [comment]
Fixed, thanks for the feedback.
