### ISSUE TITLE
develop branch

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#66]
2.5.1 has show stopping errors too. I'll submit a PR shortly.

Let's make a develop branch to avoid this.

**Comment by boc-tothefuture** [comment]
In theory we shouldn't be pushing things to master that don't work..  There should be no need for specific develop branches, each new feature can be in it's own branch with a PR. The core issue is we don't have a CI/CD pipeline verifying functionality and testing for regressions before merge.

Based on the number of regression introduced recently (mostly by me!) I am going to make that a priority.

**Comment by jimtng** [comment]
I agree in theory, but even automated testing can fail to test certain scenarios, however having it would certainly help.

I noticed that a lot of the cucumber tests take a long time to perform. A full test run could take more than an hour to complete. We should try to optimise this. I was testing some basic things like shortening the wait time in the tests, and making the checks sleep every half a second instead of 1s to catch the changes sooner.

**Comment by boc-tothefuture** [comment]
I agree, there is a lot of room for improvement.  
The process is started [here](https://github.com/boc-tothefuture/openhab-jruby/actions) and you can see it run.
GitHub supports up to [20 concurrent jobs](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration) so we should be able to run each feature file in parallel to significantly reduce the overall time.

**Comment by boc-tothefuture** [comment]
I am starting to work on the parallelization.

**Comment by boc-tothefuture** [comment]
Executes in under 14 minutes: https://github.com/boc-tothefuture/openhab-jruby/actions/runs/484229018

There is probably ample room for optimization still.  But I think that is a sufficient start.
