### ISSUE TITLE
Add living documentation to the docs

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#73]
Integrate the BDD living documentation into the official docs to provide examples that are always up to date for how the features/functions work.

**Comment by jimtng** [comment]
What/where is the BDD living documentation, and where does it go within the official docs?

**Comment by boc-tothefuture** [comment]
I haven't had a chance to play with it, but [pickles](https://www.picklesdoc.com/#what_does_pickles_do) can apparently output to markdown.  I am not quite sure how we would pull it in and/or embed it in the appropriate sections. But it would be nice for all our examples in the BDD to be available as examples in the docs.

**Comment by boc-tothefuture** [comment]
This is done and available here:
https://boc-tothefuture.github.io/openhab-jruby/pickles/index.html

Each section should probably be updated to point to the additional examples where appropriate.

**Comment by jimtng** [comment]
I've just noticed this. Cool output. I've also just finally googled what "BDD" means: https://cucumber.io/docs/bdd/

At the very least we could have a link to it if not already, from the main docs page. The docs site needs a bit of tidy up (fix footer, etc)

**Comment by jimtng** [comment]
@boc-tothefuture can this issue be closed, or did you envision something more than what is currently in place?

**Comment by boc-tothefuture** [comment]
We can close it. I left it open because the pickles team was lookinag at supporting MD which would make this format much nicer.
