### ISSUE TITLE
Easier way to reorder docs

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#74]
Great work on the new doc structure. I was adding a page for metadata, but noticed that in order for me to insert a page inbetween or at the top of the list, I'd have to go through all the other pages and change all the nav_order manually. Is there an easier way?

**Comment by boc-tothefuture** [comment]
No easier way that I am aware of.  It is either alphabetical or you specify the order in the front matter.

**Comment by boc-tothefuture** [comment]
Can we close this @jimtng ?
