### ISSUE TITLE
items["Group"] not supported

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#76]
I noticed that groups are specifically rejected / not included in `items[]`. Is there a reason for this?

I need to access a group item based on its name, and not sure how else to do it.

**Comment by jimtng** [comment]
After further digging, I found that groups are contained in the `groups["groupname"]` variable. However I couldn't send a command to the group. Neither of these work:

```
groups['groupname'] << ON
groups['groupname'].command ON
```

**Comment by jimtng** [comment]
This relates to #58, #48 because Group is implemented using a custom class, as well as NumberItem, and StringItem, so they don't benefit from the current monkeypatching on `Java::OrgOpenhabCoreItems::GenericItem`. They all should, because we'll need to access metadata, persistence etc on Groups, NumberItem, StringItem, etc.

I hope this could be the next focus now that we've got a nice docs and CI system in place. Not to say that the osgi / metadata / actions / persistence aren't important. :)

**Comment by jimtng** [comment]
> However I couldn't send a command to the group

I just now remembered that in another issue, the current solution was to send the command to each group members, i.e. `group.each(&on)`. It's just that I'm so used to being able to send the command to the group itself in rulesdsl / jython.

**Comment by boc-tothefuture** [comment]
We should be able to send commands to the group, so that is a defect.  They aren't part of the items list because I view them as distinct from items, so we can access them with groups.  

Redoing the items so they are consistent is a goal.  Right now I am in the middle of adding YARD documentation to all methods and classes and trying to resolve all rubocop violations so we can start enforcing rubocop in the build process to keep the code clean.  I would say I am 50% complete on the YARD documentation.

**Comment by boc-tothefuture** [comment]
Can we close this one?  I think we have a defect open that we can't send commands to groups.

**Comment by jimtng** [comment]
> They aren't part of the items list because I view them as distinct from items, so we can access them with groups.

Should we keep groups separate from items[]? Jython puts groups in items[] too.



> Can we close this one? I think we have a defect open that we can't send commands to groups.

This issue is mainly about items['groupname'] so if we settle on this matter, this issue can be closed.

**Comment by jimtng** [comment]
At the very least, it should be mentioned / made clear in the docs that items[] doesn't include groups and there's a separate groups[] to access groups.

**Comment by boc-tothefuture** [comment]
> I hope this could be the next focus now that we've got a nice docs and CI system in place. Not to say that the osgi / metadata / actions / persistence aren't important. :)

I think the number one focus should be (after I complete the YARD documentation work) needs to be submitting the OpenHAB Java bundle for JRuby as that can take a long time to be approved and it would be helpful if JRuby was available to be installed as a bundle like other languages.

**Comment by jimtng** [comment]
> I think the number one focus should be (after I complete the YARD documentation work) needs to be submitting the OpenHAB Java bundle for JRuby as that can take a long time to be approved and it would be helpful if JRuby was available to be installed as a bundle like other languages.

For that, we'd need to demonstrate the usage of jruby inside the openhab gui, as that's all the rage now, not file based rules.

**Comment by jimtng** [comment]
It seems that this is by design that groups are separated out of items[] and into groups[]
