### ISSUE TITLE
Use semantic-release to automatically create changelog and version the library

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#91]
See https://github.com/semantic-release/semantic-release for details.

This would resolve the issues on conflicts in the changelog, ruby version, etc. 

Commit-lint has been installed as part of the build to check the commit messages in the PR.

**Comment by boc-tothefuture** [comment]
@jimtng - 
 I am in the middle of implementing this.  Once it is implemented I can merge your outstanding PRs. 

This should take care of a couple of things for us:
1. Auto incrementing the version number in the gem (so no conflicts for PRs)
2. Auto generating the changelog (so no conflicts for PRs)
3. Pushing the new gem out to rubygems

It has a little learning curve, so it is taking a bit.

One thing to note.. The commit message will be the exact message in the changelog.  You may want to review the open PRs and make sure that is what you want.

**Comment by jimtng** [comment]
How can we have multiple items / lines in one commit? Example:
#107 there are two entries:
fix: items['nonexistent'] now returns nil
feat: add items.include?

**Comment by jimtng** [comment]
Can the changelog include links to the issue that was fixed? Example:

Fixed
 - Multiple delayed triggers overwrite the previous triggers (#105)
 
I try to include "Fix #105", or "Resolve #xxx" in my first PR message (not in the commit string)

**Comment by boc-tothefuture** [comment]
It might automatically do the linking based on the content of the PR.  I will need to double check.

In the example above the feat and the fix should be different commits.  Can be the same PR.however.

**Comment by jimtng** [comment]
I noticed the semantic release in action just now. You might have already noticed that it didn't update the CHANGELOG.md

**Comment by boc-tothefuture** [comment]
Yep.. I was debugging that and hopefully just pushed a fix.. I hope.

**Comment by boc-tothefuture** [comment]
This appears to be working now.  Closing.
