### ISSUE TITLE
lazy loading items, groups, and things

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#94]
I'm wondering what big of a difference in performance we'd get if we weren't populating/loading all the items/groups/things on startup. I'd imagine that this process runs on each and every script file.

**Comment by boc-tothefuture** [comment]
Some more details in #88

**Comment by boc-tothefuture** [comment]
@jimtng we aren't populating/loading items/groups/things on startup.  They are only populated on demand with calls to items, things, or groups.

**Comment by jimtng** [comment]
Strange how it seems that the actions got loaded for all my things, when none was referred to in my script.

**Comment by boc-tothefuture** [comment]
Hmmm..
Did you have a call to `things[]` in there?

**Comment by jimtng** [comment]
When I didn't have things[] in my script, it doesn't load any of the thing based actions. When I did have things['mail:smtp:local'].sendMail, it would load the actions for all things, not just the one I was accessing.
