### ISSUE TITLE
docs: metadata table has a formatting issue?

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#95]
The table with the list of methods seem to be formatted incorrectly here
https://boc-tothefuture.github.io/openhab-jruby/usage/misc/metadata/

The source docs/usage/misc/metadata.md seems fine though?

**Comment by boc-tothefuture** [comment]
As you saw it needs a newline before the table.. I don't know if that is a github thing or a just the docs thing.
